### PR TITLE
confluence: use new custom AST renderer style

### LINKED ISSUE #7256: Confluence callout not formatted correctly
### Bug description

Publishing a quarto document with a callout results in callouts with a shortened line width. 

Not being able to publish callouts is a major blocker - any guidance would be greatly appreciated!

### Steps to reproduce

Create a file confluence-demo.qmd with the following.

```qmd
---
title: Confluence Demo
format: confluence-html
---

## Overview

::: {.callout-note}
Managing Confluence content with Quarto allows you to author content in Markdown, manage that content with your usual version control tools like Git and GitHub, and leverage Quarto’s tools for including computational output.
:::
```

Publish to a confluence space - 
`quarto publish confluence confluence-demo.qmd
`

### Expected behavior

image

### Actual behavior

image

### Your environment

Windows 11 

### Quarto check output

```bash
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Users\hj6\scoop\apps\quarto\current\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.4
      Path: C:/Users/hj6/AppData/Local/Programs/Python/Python39/python.exe
      Jupyter: 5.0.0
      Kernels: 

(\) Checking Jupyter engine render....Exception ignored in: <function BaseEventLoop.__del__ at 0x000001BED3980D30>
Traceback (most recent call last):
  File "C:\Users\hj6\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 683, in __del__
    self.close()
  File "C:\Users\hj6\AppData\Local\Programs\Python\Python39\lib\asyncio\selector_events.py", line 92, in close
    self._close_self_pipe()
  File "C:\Users\hj6\AppData\Local\Programs\Python\Python39\lib\asyncio\selector_events.py", line 99, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
  File "C:\Users\hj6\AppData\Local\Programs\Python\Python39\lib\asyncio\selector_events.py", line 277, in _remove_reader
    key = self._selector.get_key(fd)
  File "C:\Users\hj6\AppData\Local\Programs\Python\Python39\lib\selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "C:\Users\hj6\AppData\Local\Programs\Python\Python39\lib\selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "C:\Users\hj6\AppData\Local\Programs\Python\Python39\lib\selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "C:\Users\hj6\AppData\Local\Programs\Python\Python39\lib\selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.1.3
      Path: C:/Users/hj6/R/R-4.1.3
      LibPaths:
        - C:/Users/hj6/R/R-4.1.3/library
      knitr: 1.39
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK
```

### PR DESCRIPTION
**Pull request by cscheid**
This closes #7256.

Opening for the CI to do its thing, but the PR needs improving (specifically on utils.ts and custom format extensions)

### CODE REVIEW

File: tests/utils.ts [hunk 1]
```diff
@@ -25,6 +25,15 @@ export function outputForInput(
   const dir = dirname(input);
   let stem = basename(input, extname(input));
 
+  // TODO: there's a bug where output-ext keys from a custom format are
```
Comment (cscheid) [inline tests/utils.ts:28]: Hey @dragonstyle can you think of a clean way to fix this? This hack looks super ugly, but a real fix seems to need access to metadata in a way that would complicate things quite a bit.

Comment (cderv) [reply tests/utils.ts:28]: Just chiming in because I tweaked this a bit when adding typst support. `output-ext` key is recognized when passed as metadata in the yaml of the smoke test .qmd file. 
like doing  
````
format: 
  confluence-publish:
    output-ext: xml
```` 

My understanding at the time is that extension is not derived from `output-ext` value from a format, but computed from `baseFormat`. (which would be publish here). I don't think internal `output-ext` value from other non-custom format is taken into account either. 

So I think your workaround around is a good one. Otherwise, it would be like other format by adding a `if (formatDesc.baseFormat === "publish") {` handler. Not that clear. 

I may be missing something. Personally I am even fine with explicitly adding this to our test .qmd file 😅 
````yaml
format: 
  confluence-publish:
    output-ext: xml
```` 

Anyhow, I may be missing something though... 🤷‍♂️

Comment (cscheid) [reply tests/utils.ts:28]: > Just chiming in because I tweaked this a bit when adding typst support. `output-ext` key is recognized when passed as metadata in the yaml of the smoke test .qmd file. like doing
> 
> ```
> format: 
>   confluence-publish:
>     output-ext: xml
> ```

Hm. That might be the case, but we don't actually have any tests that use this syntax. If you search for `output-ext` in the repository, the only .qmd files that match are:

- tests/docs/smoke-all/2023/09/27/7041.qmd
- tests/docs/smoke-all/typst/typst-citeproc.qmd
- tests/docs/smoke-all/typst/typst-no-citeproc.qmd

All of these documents use `output-ext: typ` in the top-level of the metadata, and not in the test spec (and it changes the behavior of the rendering, not just the extension, like we discussed before)

Comment (cscheid) [reply tests/utils.ts:28]: I'm just going to merge this hack as is, and we can resolve the situation later.
