### PR TITLE
Fix code-annotation: none

### LINKED ISSUE #6332: Annotation processing in LaTeX does not respect none
````markdown
---
format:
  pdf:
    code-annotations: none
    keep-tex: true
---

```r
1 + 1 # <1>
2 + 2 
```

1. A comment

````

gives us 
image

The annotation in cell is still shown, and using the circled from because post processor still adds the replacement, and Lua filter still add command definition in preamble (contrary to #6320)

I believe this is because we don't `stripAnnotation()` but we use `replaceAnnotation()`, and the `patternEscape()` do probably too much escpaping IMO

* We should probably use `stripAnnotation` here
	https://github.com/quarto-dev/quarto-cli/blob/b13ebd7c359c5494c0ee896efbb80cc36e6ba170/src/resources/filters/quarto-pre/code-annotation.lua#L263-L265

* And `replaceAnnotation()` does not seem to work
  https://github.com/quarto-dev/quarto-cli/blob/d4f620e5cf64e4c1b767943f67825dd531de609a/src/resources/filters/quarto-pre/code-annotation.lua#L58-L60

Which probably mean than other processing does not work either even for `code-annotation: true` 🤔 
https://github.com/quarto-dev/quarto-cli/blob/b13ebd7c359c5494c0ee896efbb80cc36e6ba170/src/resources/filters/quarto-pre/code-annotation.lua#L267-L277

The `patternEscape()` call was added in https://github.com/quarto-dev/quarto-cli/commit/11f8d26e701f04bc6af1313c0b56396e58215056 but we don't test for everything there, just that the comment is coorectly replace. Which IMO happens anyway by our post processor no matter what the Lua filter is doing 
https://github.com/quarto-dev/quarto-cli/blob/49f1bd16e341f59087b346481756be50281419da/src/format/pdf/format-pdf.ts#L922-L968

@dragonstyle not sure what should really be happening specific for LaTeX. It seems we want to replace by something like ` %% ( 1 )` at some point. 🤔 Happy to discuss it with you. 

Could only be a matter of using `stripAnnotation()` or something more deep within `replaceAnnotation`

I separated it from other PR to deal with it on its own

Related to 

* https://github.com/quarto-dev/quarto-cli/discussions/6316#discussioncomment-6531415
* https://github.com/quarto-dev/quarto-cli/issues/6320 and https://github.com/quarto-dev/quarto-cli/pull/6321

### PR DESCRIPTION
**Pull request by cderv**
@dragonstyle this fix #6332 as discussed lived together 

I added a test, and also made sure that when `code-annotations: none` 
* we don't add anything in latex preamble
* We don't post process the LaTex file to leave comment unchanged

This PR also adds a fix for highlighing opt out and latex processing. I'll add test later for this.

Plan is to regroup all smoke-all test file under same folder so that we can have a clear view of all that we test for code annotation. 

I'll do that later.

### CODE REVIEW

File: src/format/pdf/format-pdf.ts [hunk 1]
```diff
@@ -364,12 +364,17 @@ function pdfLatexPostProcessor(
...
     }
-
     lineProcessors.push(captionFootnoteLineProcessor());
-    if (format.metadata[kCodeAnnotations] !== false) {
+
+    if (
+      format.metadata[kCodeAnnotations] as boolean !== false &&
+      format.metadata[kCodeAnnotations] as string !== "none"
+    ) {
+      console.log("NOT HERE");
```
Comment (dragonstyle) [inline src/format/pdf/format-pdf.ts:373]: Extra output

**Review by dragonstyle — APPROVED** [review]
Looks great other than one small extra output!

File: src/format/pdf/format-pdf.ts (hunk 1 above)
Comment (cscheid) [reply src/format/pdf/format-pdf.ts:373]: "one of us, one of us, one of us"

(I'll show myself out.)

Comment (cderv) [reply src/format/pdf/format-pdf.ts:373]: 😆 Last PR of the day,  right before going out to get the kids home 
I know I shouldn't do that in a hurry ! 🤦‍♂️ 😅

**Comment by cderv** [comment]
@dragonstyle It seems our change created an issue with your last adding test 
```
    Error running filter C:/Users/chris/Documents/DEV_R/quarto-cli/src/resources/filters/main.lua:
    ...i/src/resources/filters/./quarto-pre/code-annotation.lua:59: invalid use of '%' in replacement string
```

So after all this `patternEscape` was maybe not a bad idea, just need to adapt. 

I'll look closer.

**Comment by cderv** [comment]
Issue is with language using `%` as comment chars. This obviously does not play well with Lua regex.

**Comment by cderv** [comment]
Ok I think I got it - we have some comment chars in some language that have a `%` char, and as we are using those for replacement string we need to escape them. 

I think that is why you add `patternEscape()`. I see now the function I added does the same but only for percent. However, it seems you can't use `patternEscape` for replacement string because it puts to much % and the rule from http://www.lua.org/pil/20.2.html does not apply. I think this is because `%` in gsub replacement has special meaning for position of capture like `%1` or `%s`
http://www.lua.org/pil/20.3.html

> The third use of captured values is in the replacement string of gsub. Like the pattern, the replacement string may contain items like '%d', which are changed to the respective captures when the substitution is made. (By the way, because of those changes, a `%´ in the replacement string must be escaped as "%%".)

The fix is not perfect because applying a replacement with position like `percentEscape("%1")` will modify it. 
Though I believe for our usage here we don't use special position pattern `%n` in replacement string build from comment char.

Does it seems ok ?
