### PR TITLE
fix: remove trailing / from site-url and ensure canonical gets one

### LINKED ISSUE #9524: canonical-url includes double // and no trailing slash
### Bug description

Given a Quarto project configuration:

```yaml
project:
  type: website

website:
  site-url: https://quarto.org/

format:
  html:
    canonical-url: true
```

The `about/index.qmd` file receives the following tag:

```html
<link rel="canonical" href="https://quarto.org//about">
```

This link tag has two problems:

1. Double slash when concatenating `site-url` with the page path.
2. Missing trailing slash (causing an unnecessary redirect).

### Steps to reproduce

Create a Quarto project with an index file in a subdirectory. Render that project. Look at the generated HTML.

### Expected behavior

```html
<link rel="canonical" href="https://quarto.org/about/">
```

### Actual behavior

```html
<link rel="canonical" href="https://quarto.org//about">
```

### Your environment

_No response_

### Quarto check output

```
Quarto 1.4.551
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.551
      Path: /Users/aron/quarto/quarto-1.4.551-macos/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: /opt/homebrew/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
```

### PR DESCRIPTION
**Pull request by mcanouil**
This pull request fixes the issue where a trailing slash was not being removed from the site URL. The `synthesizeCitationUrl` function now removes the trailing slash from the base URL before constructing the citation URL.

<details><summary>Outdated</summary>
<p>

I did not change the "else" part because I was unsure how to trigger this part of the codepath, but using the same if/else condition on length would not hurt I believe.

```diff
    } else {
      const relativePath = relative(
        rootDir,
        join(dirname(input), basename(outputFile)),
      );
      const part = pathWithForwardSlashes(relativePath);
+     if (part.length === 0) {
-     return `${baseUrl}/${part}`;
+       return `${baseUrl}/${part}`;
+     } else {
+       return `${baseUrl}/${part}/`;
+     }
    }
```

</p>
</details> 

Fixes #9524

### CODE REVIEW

**Comment by cscheid** [comment]
(Note the failing tests.)

**Comment by cscheid** [comment]
This suggestion doesn't work.

Use the following as a test:

## _quarto.yml

```yml
project:
  type: website

canonical-url: true

website:
  site-url: https://index.html.com/
  title: "Test-9595"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```

You'll see that about.html gets a broken canonical URL: 

```
<link rel="canonical" href="https://index.html.com/about.html/">
```

**Comment by mcanouil** [comment]
Weird, as I don't get this result using this current PR with the two additional commits.
image

**Comment by mcanouil** [comment]
I've still got an issue though but not for index related files.

**Comment by cscheid** [comment]
The later commits fixed it.

**Comment by mcanouil** [comment]
Yep, I did not realised, the else part always returned the file, so trailing / was not needed.
My reprex has no issues and tests were fine locally.
image

Waiting for CI to confirm.

**Comment by cscheid** [comment]
I'd like some unit or smoke tests here.

Can you create a website project under 2024/05/06, configure it like above, and then test the contents of index.qmd and about.qmd? You can use `tests/docs/smoke-all/2024/04/17/9356` as a template. (I think you'll need to use `ensureFileRegexMatches` instead of `ensureHtmlElements`, though)

**Comment by mcanouil** [comment]
I'll add the test probably on wednesday.

**Comment by cscheid** [comment]
> (I think you'll need to use `ensureFileRegexMatches` instead of `ensureHtmlElements`, though)

**Comment by mcanouil** [comment]
I don't understand why the tests are failing for subdirectories but not for root documents.
The resulting HTML documents do contain the values but somehow the same regex test does not behave the same way.
I am very confused here.

**Comment by cderv** [comment]
> I don't understand why the tests are failing for subdirectories but not for root documents.

I think this is just because our smoke all testing don't support this organization for projects. Your current test project is not something that `smoke-all.tests.ts` support. So it requires to improve and add support. 

See the path in error log
````
Inspecting docs/smoke-all/2024/05/06/9524/about/test/_site/something.html for Regex matches
````
- Look at where you project lives (`docs/smoke-all/2024/05/06/9524/`)
- Where the subdirectory file is supposed to be (in `about/test`) 
- What is the project output dir  (`_site`)

You see that the path created as output for the file to test is wrong, so you get the `No such file or directory` error. 

This is because we don't support subdirectory in project we tests in smoke-all 
https://github.com/quarto-dev/quarto-cli/blob/3b4cdd3a211b6a81caf2b27a41512301490a43ec/tests/utils.ts#L89-L94

We build the path without accounting for possibly subdirectories for the input. 

So two solutions: 
- Don't do smoke-tests but regular ts test, where you get more control on which file to tests
- Make adaptation to `outputForInput()` and possibly other places to fix this project testing with smoke-all 

Hope it helps understand

**Comment by cscheid** [comment]
@mcanouil Responding to https://github.com/quarto-dev/quarto-cli/issues/9524#issuecomment-2153474148 here since it's more relevant:

The test suite still isn't passing, right?

**Comment by mcanouil** [comment]
Yes, because website project subdirectories does not meet test setup workflow as explained by Christophe.
So the smoke test does not seem suited to test this which would need to test in a real project.

**Comment by cderv** [comment]
Let me try to adapt the test here.

**Comment by cderv** [comment]
So I have done the work in an other PR: 
* https://github.com/quarto-dev/quarto-cli/pull/9969

When this is merged, the test here should pass, possibly without change as it will now behave as expected.

**Comment by cscheid** [comment]
Should just be a matter of merging this against main in the PR branch, then, so the test suite runs with the new changes?

File: src/quarto-core/attribution/document.ts
Comment (cderv) [inline src/quarto-core/attribution/document.ts:1]: Just so you know, we have some helpers in our code base.

- `removeTrailingSlash`
- `ensureTrailingSlash`


Combined with `pathWithForwardSlashes` and `join`, they allow to build path quite safely. They usually are used to deal with path having or not `/` trailing slash

So 
````
      return `${removeTrailingSlash(baseUrl)}/${
        pathWithForwardSlashes(relative(rootDir, dirname(input)))
      }`;
````

could have been something like this probably 
````
      return `${baseUrl}/${
        pathWithForwardSlashes(relative(rootDir, dirname(input)))
      }`;
````


Anyhow, your solution works, just mentioning them so that you know we have them.

File: tests/docs/smoke-all/2024/05/06/9524/about/file.qmd [hunk 1]
```diff
@@ -0,0 +1,10 @@
+---
+title: "Untitled"
+_quarto:
+  tests:
+    html:
+      ensureFileRegexMatches:
+        - ['<link rel="canonical" href="https://index.html.com/about/file.html">']
```
Comment (cderv) [inline tests/docs/smoke-all/2024/05/06/9524/about/file.qmd:7]: Can't we use `ensureHtmlElements` to be safer than using Regex ?

**Comment by cderv** [comment]
@mcanouil All test have passed now. So this should be good. 

PR is draft - did you get anything to do before we merge ?

**Comment by mcanouil** [comment]
I put it in draft because of the failing tests, so ready it is since the changes were made in `main`.

**Comment by cderv** [comment]
I'll rebase and merge. Thanks !

File: tests/docs/smoke-all/2024/05/06/9524/about/file.qmd (hunk 1 above)
Comment (cderv) [reply tests/docs/smoke-all/2024/05/06/9524/about/file.qmd]: I have done the change
