### PR TITLE
fix: underscore in code cell `filename` attribute in latex/pdf

### LINKED ISSUE #6990: Underscore in code cell `filename=` causes an error in LaTeX rendering Missing $
### Bug description

It seems that when there is an underscore `_` in the filename key of a .qmd cell code, LaTeX cannot render the file correctly, as it expect `_` to be in math mode.

 
 ```text
 compilation failed- error
Missing $ inserted.
<inserted text> 
                $
l.197 \caption{\texttt{my_example.r}}
                                      

You may need to $ $ around an expression in this file.
see notebooks/test.log for more information.
```

### Steps to reproduce

For instance, the following .qmd file would produce the error, with `quarto render`
 
````qmd
---
format: pdf
---

```{.r filename="my_example.r"}
replicate(sample(1:10), 10)
```
````

### Expected behavior

When I write filename with underscore in quarto code cell, I want it to be LaTeX compilable.

### Actual behavior

An underscore in the `filename` directive makes the LaTeX compilation fail.

### Your environment

- IDE: VSCode, from CLI.
- Fedora 38

### Quarto check output

I have updated to latest quarto github release, and the problem is still here apparently:

✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /usr/bin/python3
      Jupyter: 5.3.0
      Kernels: ir, julia-1.9, python3

(-) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/lib64/R
      LibPaths:
        - /home/sortion/R/x86_64-redhat-linux-gnu-library/4.3
        - /usr/lib64/R/library
        - /usr/share/R/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK

### PR DESCRIPTION
**Pull request by mcanouil**
This PR adds an exception to escape underscore when the format is LaTeX in filename code cell attribute.
 
Fixes #6990

image

### CODE REVIEW

File: src/resources/filters/quarto-pre/code-filename.lua [hunk 1]
```diff
@@ -10,6 +10,9 @@
 
 function code_filename()
   local function codeBlockWithFilename(el, filename)
+    if quarto.doc.is_format("latex") then
+      filename = string.gsub(filename, "_", "\\_")
+    end
```
Comment (cderv) [inline src/resources/filters/quarto-pre/code-filename.lua:15]: I think format specific stuff for DecoratedCodeBlock are best put inside the renderer itself. 
I would put this inside https://github.com/quarto-dev/quarto-cli/blob/7dab87bbabd8f8193ae4ff58b9891c6f015d0c49/src/resources/filters/customnodes/decoratedcodeblock.lua#L66-L70

Also I don't know if there could be other escaping needed, but we have a `stringEscape` we use for caption in LaTeX already. 
https://github.com/quarto-dev/quarto-cli/blob/7dab87bbabd8f8193ae4ff58b9891c6f015d0c49/src/resources/filters/quarto-pre/table-captions.lua#L223C1-L225

This would cover `_` and also other required escaping probably

Comment (mcanouil) [reply src/resources/filters/quarto-pre/code-filename.lua]: Using `escapeString` works properly 6eb06fb41c421e5f1a418c49af871f4942fc5a22

**Comment by cscheid** [comment]
This looks good, but could you add a regression test?

The files in `tests/docs/smoke-all` should be a guide. Specifically, look for

```
_quarto:
  tests:
    latex:
      ensureFileRegexMatches:
         ...
```

to make sure that we document the behavior and don't regress on this in the future.

**Comment by mcanouil** [comment]
@cscheid I added the unit test for this for LaTeX/HTML formats.

**Review by cscheid — APPROVED** [review]
Great, thank you!
