### PR TITLE
listing - Correctly handle non ASCII category and special characters

### LINKED ISSUE #8517: listing categories with `'` in them can't be clicked on
I'll come up with a full example soon, but I think this should trigger it.

Create a listing like this:

````
---
title: "log"
listing:
  contents: 
    - "2024-*.qmd"
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
  feed: true
page-layout: full
title-block-banner: true
---
````

then in one of the posts add a category like this:

````
---
title: "2024-01-01"
categories:
  - i'm-an-idiot
  - other
---
````

That category will show up on the listings sidebar but can't be clicked on, and if you click on `other`, this post won't be part of the filtered subset.

### LINKED ISSUE #11358: ERROR: InvalidCharacterError: The string to be encoded contains characters outside of the Latin1 range.
### Bug description

```sh
$ quarto render posts/2024-11-11-random/index.qmd 
[1/2] posts/2024-11-11-random/index.qmd
[2/2] index.qmd
ERROR: InvalidCharacterError: The string to be encoded contains characters outside of the Latin1 range.

Stack trace:
    at btoa (ext:deno_web/05_base64.js:52:13)
    at Object.utilities.metadataAttrs (file:///opt/quarto/bin/quarto.js:98020:34)
    at eval (eval at <anonymous> (file:///opt/quarto/bin/quarto.js:3925:16), <anonymous>:51:29)
    at renderEjs (file:///opt/quarto/bin/quarto.js:90595:18)
    at include (file:///opt/quarto/bin/quarto.js:90606:28)
    at partial (eval at <anonymous> (file:///opt/quarto/bin/quarto.js:3925:16), <anonymous>:9:40)
    at eval (eval at <anonymous> (file:///opt/quarto/bin/quarto.js:3925:16), <anonymous>:13:2)
    at renderEjs (file:///opt/quarto/bin/quarto.js:90595:18)
    at templateMarkdownHandler (file:///opt/quarto/bin/quarto.js:97842:28)
    at markdownHandler (file:///opt/quarto/bin/quarto.js:98800:24)
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Actual behavior

_No response_

### Your environment

- OS: Ubuntu 22.04

### Quarto check output

```
$ quarto check
Quarto 1.6.33
[✓] Checking environment information...
      Quarto cache location: /home/wsx/.cache/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.33
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2021

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.7 (Conda)
      Path: /home/wsx/miniconda3/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /usr/local/lib/R
      LibPaths:
        - /home/wsx/R/x86_64-pc-linux-gnu-library/4.4
        - /usr/local/lib/R/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```

### PR DESCRIPTION
**Pull request by cderv**
This is additional fix to #11177 so that category with special characters, and UTF-8 characters are correctly handled.

It fixes first #11358 and then add to #11177 to fix #8517. A category with apostrophe does not cause issue anymore (#10829) but cliking on them was still not working. 

### About UTF-8 in category

Using base64 encoding works, in the limite of ASCII character range. For content with UTF-8 characters, we need to take extra measure. 

This PR uses `encodeURIComponent` and `decodeURIComponent` to get into that range of characters. It seems UTF-8 stream can be used, so we could switch to that. 

### About clicking on category with special char

It took me a while to find the problem but the issue was that 

- `categories` are metadata processed by us in JS, but also passed to Pandoc to use in title-block template. 
- Pandoc parses any string value in metadata as Markdown, and we default to `markdown+smart` for the readers. This smart extension applies and so `'` was transformed to another character. 
- This lead to our JS script not being able to find the right category to activate because they are not the same when base64 encoded. 

	<details>
	<summary>Example </summary>
	
	````markdown
	---
	title: "Font test"
	categories: "apos'trophe"
	---
	
	test
	````
	
	Render to native
	````
	Pandoc
	  Meta
	    { unMeta =
	        fromList
	          [ ( "categories" , MetaInlines [ Str "apos\8217trophe" ] )
	          , ( "title"
	            , MetaInlines [ Str "Font" , Space , Str "test" ]
	            )
	          ]
	    }
	  [ Para [ Str "test" ] ]
	````

	`\8217` is not `'`
	
	</details>

We had such issues in the past with `revealjs-url` metadata, so I am using same "trick" by wrapping in `pandocNativeStr()` so that it can be passed unparsed as a metadata to Pandoc. 

This requires processing the format metadata to override the existing one. To do that
- it is using `projectExtras` as this really apply to website project. 
- it is using a `metadataOverride` though because currently `mergeConfigs` is appending arrays together otherwise. 
- There needs to be a special handle in the (again) problematic `engineMetadata` override. As discussed in the past, I think this should be removed, but that it is not the place to discuss. Fact is `categories` is not listed as a `isQuartoMetadata()` so, it does get identified as possible engine metadata override, but it can't happen here as we are processing it. So like revealjs `theme` key, there is an exception now. **This whole part will need to be reconsider when we'll deal with `mergeConfig` and this code piece**

Hopefully this explains clearly what I tried. Happy to discuss and consider another solution if you think of one. 

Consequence of this change: `categories` can only be raw string, as in non-markdown string. Which I think is what we currently expect (but not enforced until now)

### CODE REVIEW

File: src/core/base64.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+export function b64EncodeUnicode(str: string) {
+  return btoa(encodeURIComponent(str));
+}
+
+export function UnicodeDecodeB64(str: string) {
```
Comment (cscheid) [inline src/core/base64.ts:5]: let's make that function lowercase `unicode` instead of `Unicode`
