### PR TITLE
postprocess revealjs slides so that anchor clicks resolve correctly

### LINKED ISSUE #3533: Hyperlinks of equation numbers do not work in quarto presentation (revealjs)
### Bug description

For the quarto presentation (revealjs),
we will move to the first page if we click the hyperlinks of equation numbers.

It is OK for other hyperlinks, e.g. Theorem.

The following is an easy test `qmd` file.

```
---
title: "Untitled"
format: revealjs
---

## A

$$
\begin{aligned}
  f(X) = y.
\end{aligned}
$$ {#eq-EEE}

## B
  
See @eq-EEE.

::: {#thm-TTT}
Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.
:::

## C

See @thm-TTT.
```

My device:
- RStudio 2022.07.2 Build 576
- quarto version: 1.2.269

-
  ```
  > sessionInfo()
  R version 4.2.2 (2022-10-31 ucrt)
  Platform: x86_64-w64-mingw32/x64 (64-bit)
  Running under: Windows 10 x64 (build 19044)
  ```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

### PR DESCRIPTION
**Pull request by cscheid**
Closes #3533.

### CODE REVIEW

File: src/format/reveal/format-reveal.ts [hunk 1]
```diff
@@ -682,6 +682,23 @@ function revealHtmlPostprocessor(
...
+    const anchors = doc.querySelectorAll("a[href^='#/']");
+    for (const anchor of anchors) {
+      const anchorEl = anchor as Element;
+      const href = anchorEl.getAttribute("href");
+      if (href) {
+        const target = doc.getElementById(href.replace(/^#\//, ""));
+        if (target) {
+          const slide = findParentSlide(target);
+          if (slide) {
+            anchorEl.setAttribute("href", `#/${slide.getAttribute("id")}`);
```
Comment (cscheid) [inline src/format/reveal/format-reveal.ts:696]: My only question, @jjallaire, is whether I can safely assume a slide to always have an `id`.

Comment (jjallaire) [reply src/format/reveal/format-reveal.ts:696]: In our default settings they will always have an ID but it's possible the user could create a config where they don't. I'd just do a further check on the id before setting the `href`
