### PR TITLE
search for tags and branches. Closes #1836

### LINKED ISSUE #1836: [FR] Quarto extension and Github subdirectory
I open the issue to keep track of this here instead/in addition to the discussion.
To note, the repository from the origin discussion no longer exists.

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1440

<div type='discussions-op-text'>

<sup>Originally posted by **mcanouil** July 17, 2022</sup>
Hi,

does Quarto extensions/formats have to be alone in a Github repository?
I wanted to store several formats in one repository (https://github.com/mcanouil/quarto-ext) and apparently this is not currently possible.

```bash
quarto install extension mcanouil/quarto-ext/coeos
# Quarto extensions may execute code when documents are rendered. If you do not 
# trust the authors of the extension, we recommend that you do not install or 
# use the extension.
#  ? Do you trust the authors of this extension (Y/n) › Yes
# ERROR: TypeError: Invalid URL
```

Did I miss something when we want a subdirectory?
</div>
</br>
<div type='discussions-op-text'>

<sup>Originally posted by **dragonstyle** July 17, 2022</sup>

Definitely- we should either support subdirectories or perhaps allow targeting / selection of specific extensions within the same repo. Seems useful!

</div>

### PR DESCRIPTION
**Pull request by cscheid**

### CODE REVIEW

File: src/core/download.ts [hunk 1]
```diff
@@ -14,17 +14,20 @@ export interface DownloadError extends Error {
...
   toFile: string,
 ) {
   // Fetch the data
-  const response = await fetch(
-    url,
-    {
-      redirect: "follow",
-    },
-  );
+  console.log(url);
```
Comment (jjallaire) [inline src/core/download.ts:22]: Stray `console.log()`

Comment (cscheid) [reply src/core/download.ts]: I dropped all the other ones 🤦 fixed. sorry.
