### PR TITLE
themes: use content hash in cache key and output file name

### LINKED ISSUE #10369: dashboard in a website sharing scss from an extension
### Bug description

Building a website with a dashboard in one page functions well ; but things get messy when trying to style it through an extension (and the logic is not easy to grasp). In this exemple, the html format is styled with an extension (called ext), setting some yaml and refering to a `.scss` file. Everything is fine, but the dashboard is not styled. However, when adding in the extension `_extension.yml` a dashboard section, using the same theme/.scss as the html part, then the theming and scss are applied everywhere including the dashboard. That's working, but a bit circonvoluted and not coherent with theming directly html format in the `_quarto.yml`. I may be missing something however.

A exemple:

`_quarto.yml:`
````yml
project:
  type: website

website:
  title: "test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Dashboard
      - about.qmd

format:
  html: 
    theme: cosmo
````

`index.qmd`
````qmd
---
title: "test"
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

```{r}
1 + 1
```
````

`dashboard.qmd`
````qmd
---
format:
  dashboard: default
---
## Row
::: {.valuebox title="title" color="green"}
42
:::

::: {.valuebox title="title" color="orange"}
76
:::
````

a random `about.qmd`

But if I use an extension, in 

`_extension/ext/ext/_extension.yml` with a scss file setting some elements (as a matter of fact it is not needed)
````yml
title: myext
author: me
version: 0.1.0
quarto-required: ">=1.6.3"
contributes:
  formats:
    html:
      theme: 
        - cosmo
        - myscss.scss
      mainfont: Open Sans
      toc-location: left
      lightbox: true
      title-block-style: default
````

and then use the folowing `_quarto.yml`, then the styling works everywhere except on the dashboard
````yml
project:
  type: website
website:
  title: "test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Dashboard
      - about.qmd
format:
  ext-html: 
    theme: cosmo
````

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Actual behavior

_No response_

### Your environment

RStudio 2024 08
Quarto 1.6.3
Mac OS

### Quarto check output

```bash
Quarto 1.6.3
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.3
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/local/bin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.48
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK
```

### PR DESCRIPTION
**Pull request by cscheid**
This fixes one of the longstanding Quarto SCSS bugs with theming.

Now, different files in the same website can have different themes and they will each have their own CSS file.

This currently applies to:

- `bootstrap.min.css`, which is now emitted as `bootstrap-${hash}.min.css`, where `hash` is the MD5 hash of the _output_. This file is generated by `html` and `dashboard` both.
- `quarto.css`, the name of the css file in revealjs themes.
- `quarto-syntax-highlighting.css`, the CSS file responsible for syntax highlighting.

We need unit and regression tests as well as a whole lot of early user testing on this one.

This closes #10369, #10087, #8383 (and likely others that I haven't found)

### CODE REVIEW

File: src/command/render/render-contexts.ts [hunk 1]
```diff
@@ -507,31 +507,31 @@ async function resolveFormats(
...
+      //       directoryFormat.metadata[kTheme],
+      //       projFormat.metadata[kTheme],
+      //     )
+      //   ) {
+      //     warnOnce(
+      //       `The file ${file.path} contains a theme provided by a metadata file. This theme metadata is being ignored. Website projects do not support per directory themes since all pages within a website share the website's theme.`,
+      //     );
+      //   }
+      //   delete directoryFormat.metadata[kTheme];
+      // }
```
Comment (cderv) [inline src/command/render/render-contexts.ts:534]: In relation with my other comments, do I understand correctly quarto will now no more consider that project-level bootstrap theme wins over any document theme ? 

This is mainly to understand correctly, and be sure we document correctly this change, as potentially "breaking" change, and give advices for users on how to adjust in their website.

**Review by cderv — COMMENTED** [review]
Really nice fix for the revealjs problem ! Thanks a lot. 

I want to open a discussion on some other change for websites and bootstrap themes. I commented below, but we can also discuss this live - could be easier than in writing here. 

I mostly want to make sure I understand correctly the impact, as I though current design choice was Bootstrap website themes should always win.

File: src/format/dashboard/format-dashboard.ts [hunk 2]
```diff
@@ -110,7 +110,10 @@ export function dashboardFormat() {
           const formats: Record<string, Metadata> = format.metadata
             .format as Record<string, Metadata>;
           const htmlFormat = formats["html"];
-          if (htmlFormat && htmlFormat[kTheme]) {
+          const dashboardFormat = formats["dashboard"];
+          if (dashboardFormat && dashboardFormat[kTheme]) {
+            format.metadata[kTheme] = dashboardFormat[kTheme];
+          } else if (htmlFormat && htmlFormat[kTheme]) {
```
[the remark this answers is not in the document]
Comment (cscheid) [reply src/format/dashboard/format-dashboard.ts:116]: > Is this change meant to pick up any dashboard theme format defined at project level ?

This relates to the question I asked on Slack yesterday:

- Before this PR, an `html` theme would be picked up by the `dashboard` format and used.
- With this PR and without this specific change, themes need to be set to `dashboard` specifically, even if they were set in the `html` format. This is a change from the 1.5 behavior
- With this PR and with this specific change, a theme set to `html` will affect `dashboard`, mimicking the 1.5 behavior. Changing the theme specifically in `dashboard` works, and overrides the theme for dashboards in case it exists for HTML.

File: src/command/render/render-contexts.ts (hunk 1 above)
Comment (cscheid) [reply src/command/render/render-contexts.ts:534]: > do I understand correctly quarto will now no more consider that project-level bootstrap theme wins over any document theme ?

You have it slightly wrong. It's not that project-level bootstrap won over any document theme. It's that document-level themes _were disabled_. They no longer need to be.

And then, yes: themes in documents now override themes in projects. This is now consistent with our general idea of configuration behavior defaults. From more general to more specific: ambient to project to document to code cells.

File: src/format/dashboard/format-dashboard.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (cderv) [reply src/format/dashboard/format-dashboard.ts:116]: Thanks a lot for the clear explanation. That makes sense - I see now the specific of third bullet point. 

IMO we need to highlight this change and the impact. But it definitely makes sense to have this behavior now. Thank you

File: src/command/render/render-contexts.ts (hunk 1 above)
Comment (cderv) [reply src/command/render/render-contexts.ts:534]: You are right - I think I missed the disabled part. I was not really possible to do differently before so we disabled, and now that we can do it, we want to enable the document overrides. 

It can appear as a change in design and could lead to breaking change for anyone having configuration that were disabled previously. 

So I think we need to hightlight this so that users can check there website projects, and know what to do if they see undesired differences. 

Thank you for the explanation.

**Comment by dragonstyle** [comment]
🔥 awesome and a lot shorter than I expected!
