### PR TITLE
Asciidoc floatreftarget fixes

### LINKED ISSUE #8055: Table and figure captions not working in AsciiDoc
### Bug description

The latest pre-release of Quarto (v1.4.533) produces AsciiDoc syntax that causes figure and table captions to be disconnected. The captions appear as a numbered list with a single item. This problem does not exist for HTML and PDF outputs.

### Steps to reproduce

Save the following code to *caption.qmd*.

````qmd
---
title: Caption
---

@tbl-fruit shows just how expensive fruit is these days.

fruit| price
-----|-----:
apple|2.05
pear|1.37
orange|3.09

: Various fruits and their prices {#tbl-fruit}


And if that's not convincing, consider @fig-fruit.

```{mermaid}
%%| label: fig-fruit
%%| fig-cap: Pretty convincing
flowchart LR
  A[Hard edge] --> B(Round edge)
  B --> C{Decision}
  C --> D[Result one]
  C --> E[Result two]
```

Fin.
````

### Expected behavior

I'm not exactly sure what the correct AsciiDoc syntax is, but the latest Quarto release (v1.3.450) produces: 

```
= Caption

<<tbl-fruit>> shows just how expensive fruit is these days.

[[tbl-fruit]]
.Various fruits and their prices
[cols=",>",options="header",]
|===
|fruit |price
|apple |2.05
|pear |1.37
|orange |3.09
|===

And if that’s not convincing, consider <<fig-fruit>>.

.Pretty convincing
[#fig-fruit]
image:caption_files/figure-asciidoctor/mermaid-figure-1.png[caption_files/figure-asciidoctor/mermaid-figure-1,width=550,height=133]

Fin.
```

### Actual behavior

The command:

```
$ quarto render caption.qmd --quiet --to asciidoc --output -
```

Produces:

```
= Caption

<<tbl-fruit>> shows just how expensive fruit is these days.

. Various fruits and their prices
[[tbl-fruit]]
====

[cols=",>",options="header",]
|===
|fruit |price
|apple |2.05
|pear |1.37
|orange |3.09
|===

====

And if that’s not convincing, consider <<fig-fruit>>.

. Pretty convincing
[[fig-fruit]]
====

image:caption_files/figure-asciidoc/mermaid-figure-1.png[caption_files/figure-asciidoc/mermaid-figure-1,width=550,height=133]

====

Fin.
```

### Your environment

OS: macOS Monterey 12.5

### Quarto check output

```
Quarto 1.4.533
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.533
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.12
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/jeroen/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: /Users/jeroen/.pyenv/versions/3.11.1/bin/python3
      Jupyter: 5.3.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

### PR DESCRIPTION
**Pull request by cscheid**
Closes #8055.

I'm not confident that we're generating the correct output here, but given the reported .qmd, our output in this branch is:

````
= Caption

<<tbl-fruit>> shows just how expensive fruit is these days.

[[tbl-fruit]]
.Various fruits and their prices
[cols=",>",options="header",]
|===
|fruit |price
|apple |2.05
|pear |1.37
|orange |3.09
|===

And if that’s not convincing, consider <<fig-fruit>>.

.Pretty convincing
[#fig-fruit]
image::8055_files/figure-asciidoc/mermaid-figure-1.png[Pretty convincing,width=550,height=133]

Fin.
````

### CODE REVIEW

File: src/resources/filters/customnodes/floatreftarget.lua [hunk 1]
```diff
@@ -787,9 +787,44 @@ end, function(float)
...
+  if float.type == "Figure" then
+    local count = 0
+    local img
+    _quarto.ast.walk(float.content, {
+      Image = function(node)
+        count = count + 1
+        img = node
+      end
+    })
+    if count == 1 then
```
Comment (cderv) [inline src/resources/filters/customnodes/floatreftarget.lua:811]: This is to let subfigures pass through right ?

File: src/resources/filters/customnodes/floatreftarget.lua [hunk 2]
```diff
@@ -787,9 +787,44 @@ end, function(float)
...
+  end
+
+  quarto.log.output(float)
+  quarto.log.output(float.content)
+
+  -- Fallthrough case, render into a div.
+  float.caption_long.content:insert(1, pandoc.RawInline("asciidoc", "."))
   float.caption_long.content:insert(pandoc.RawInline("asciidoc", "\n[[" .. float.identifier .. "]]\n===="))
-  return pandoc.Div({
+  return pandoc.Blocks({
```
Comment (cderv) [inline src/resources/filters/customnodes/floatreftarget.lua:827]: I believe there is an issue with this. Simple test for subfigures.

````markdown
---
title: Caption
format: 
  asciidoc: default
  html: default
---

::: {#fig-try}

![Test](surus.png)

![Test2](surus.png)

Hello
:::

````

<details>
<summary>Lua error</summary>

````
Error running filter C:\Users\chris\DOCUME~1\DEV_R\QUARTO~2\src\resources\filters\main.lua:
Block, list of Blocks, or compatible element expected, got table
	while retrieving function argument blocks
	while retrieving arguments for function Blocks
stack traceback:
	...2\src\resources\filters\./customnodes/floatreftarget.lua:825: in field 'render'
	...~1\DEV_R\QUARTO~2\src\resources\filters\./ast/render.lua:45: in local 'filter_fn'
	...V_R\QUARTO~2\src\resources\filters\./ast/customnodes.lua:164: in function <...V_R\QUARTO~2\src\resources\filters\./ast/customnodes.lua:154>
	(...tail calls...)
	[C]: in ?
	[C]: in method 'walk'
	...V_R\QUARTO~2\src\resources\filters\./ast/customnodes.lua:86: in function <...V_R\QUARTO~2\src\resources\filters\./ast/customnodes.lua:76>
	(...tail calls...)
	..._R\QUARTO~2\src\resources\filters\./ast/runemulation.lua:82: in local 'callback'
	..._R\QUARTO~2\src\resources\filters\./ast/runemulation.lua:97: in upvalue 'run_emulated_filter_chain'
	..._R\QUARTO~2\src\resources\filters\./ast/runemulation.lua:133: in function <..._R\QUARTO~2\src\resources\filters\./ast/runemulation.lua:130>
stack traceback:
	...V_R\QUARTO~2\src\resources\filters\./ast/customnodes.lua:86: in function <...V_R\QUARTO~2\src\resources\filters\./ast/customnodes.lua:76>
	(...tail calls...)
	..._R\QUARTO~2\src\resources\filters\./ast/runemulation.lua:82: in local 'callback'
	..._R\QUARTO~2\src\resources\filters\./ast/runemulation.lua:97: in upvalue 'run_emulated_filter_chain'
	..._R\QUARTO~2\src\resources\filters\./ast/runemulation.lua:133: in function <..._R\QUARTO~2\src\resources\filters\./ast/runemulation.lua:130>
ERROR: Error
    at renderFiles (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/render-files.ts:346:23)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async renderProject (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/project.ts:268:23)
    at async renderForPreview (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/preview/preview.ts:436:24)
    at async render (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/preview/preview.ts:167:22)
    at async preview (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/preview/preview.ts:184:18)
    at async Command.fn (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/preview/cmd.ts:415:7)
    at async Command.execute (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/quarto.ts:155:3)
    at async file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/quarto.ts:186:5
````

</details>

Possibly because in 
````
{ 
   float.caption_long,
    -- pandoc.RawBlock("asciidoc", "[[" .. float.identifier .. "]]\n====\n"),
    float.content,
    pandoc.RawBlock("asciidoc", "====\n\n")
}
````

`float.content` is already of type `Blocks`, and you can't nest 

````
> pandoc lua -i
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
Embedded in pandoc 3.1.11
> pandoc.Blocks({pandoc.Para("Test"), pandoc.Blocks({pandoc.Para("nested")})})
Block, list of Blocks, or compatible element expected, got table
        while retrieving function argument blocks
        while retrieving arguments for function Blocks
stack traceback:
        stdin:1: in main chunk
````

BTW this is not an issue with this PR only. Using `pandoc.Div` is the same 

````
Error running filter C:\Users\chris\scoop\apps\quarto-prerelease\current\share\filters\main.lua:
Block, list of Blocks, or compatible element expected, got table
        while retrieving function argument content
        while retrieving arguments for function Div
````

**Review by cderv — COMMENTED** [review]
Thanks ! Interesting to understand more about floatreftarget. 

We probably need to more test case about what `float.content` - see my comment about the subfigures issues.

File: src/resources/filters/customnodes/floatreftarget.lua (hunk 1 above)
Comment (cscheid) [reply src/resources/filters/customnodes/floatreftarget.lua:811]: It's to make this fix as narrow as possible.

Comment (cderv) [reply src/resources/filters/customnodes/floatreftarget.lua]: ok I see. Thanks

File: src/resources/filters/customnodes/floatreftarget.lua (hunk 2 above)
Comment (cscheid) [reply src/resources/filters/customnodes/floatreftarget.lua]: > Asciidoc output probably needs to be check thoroughly for all features and probably validate or else.

We don't have a validator available, but we do have a number of asciidoc tests in `docs/smoke-all/crossrefs/float/asciidoc`.

File: src/resources/filters/customnodes/floatreftarget.lua [hunk 3]
```diff
@@ -787,9 +787,44 @@ end, function(float)
...
+      img.caption = quarto.utils.as_inlines(float.caption_long)
+      return pandoc.Figure(
+        {img},
+        {float.caption_long},
+        float.identifier)
+    end
+  end
+
+  quarto.log.output(float)
+  quarto.log.output(float.content)
```
[the remark this answers is not in the document]
Comment (cscheid) [reply src/resources/filters/customnodes/floatreftarget.lua]: Thanks, done.
