### PR TITLE
patch knitr to know about OJS chunk and its comment character so opti…

### LINKED ISSUE #5994: ojs chunk option include not working
### Bug description

Hi,
I am including a observable plot in a html document. I am used to set in the yaml as:
````
---
format:
  html:
    code-fold: true
execute:
  eval: true
  echo: true
  message: false
  warning: false
  output: true
  include: false
---
````
and selectively set the include option to true where I need it.
However, doing so, the ojs chunks does not appear when adding the //|include option, the same working perfectly when yaml include option set to true. I have also tried the `{ojs, include=TRUE}` like mermaid syntax, and all combination in between them.
Seems that the yaml option overwrite the local one?

### Steps to reproduce

````
```{r}
library(palmerpenguins)
ojs_define(data = penguins)
```

```{ojs}
//| panel: sidebar
//| include: true

viewof bill_length_min = Inputs.range(
  [32, 50], 
  {value: 32, step: 1, label: "Bill length (min):"}
)

viewof islands = Inputs.checkbox(
  ["Torgersen", "Biscoe", "Dream"], 
  { value: ["Torgersen", "Biscoe", "Dream"], 
    label: "Islands:"
  }
)

```

::: {.panel-tabset}

## Graph

```{ojs}
//| include: true
Plot.plot({
  facet: {data: filtered, 
          x: "sex",
          y: "island"},
  color: { legend: true },
  marks: [
    Plot.frame({ strokeOpacity: 0.1 }),
    Plot.dot(filtered, {
      x: "body_mass_g",
      y: "bill_length_mm",
      stroke: "species",
      tip: true
    })
  ]
})

```

## Data
```{ojs}
//| include: true

Inputs.table(filtered, {  columns: [
    "body_mass_g", "flipper_length_mm", "species","bill_length_mm"
  ]})

```
:::

```{ojs}

filtered = transpose(data).filter(function(penguin) {
  return bill_length_min < penguin.bill_length_mm &&
         islands.includes(penguin.island);
})

```
````

### Expected behavior

The ojs chunk should appear in the rendered doc when yaml option is false and chunk option are true

### Actual behavior

the ojs chunk does not appear, only the two empty tabsets

### Your environment

My settings:
````
 version  R version 4.3.0 (2023-04-21 ucrt)
 os       Windows 10 x64 (build 19045)
 system   x86_64, mingw32
 ui       RStudio
 language EN
 collate  French_France.utf8
 ctype    French_France.utf8
 tz       Europe/Paris
 date     2023-06-21
 rstudio  2023.06.0+421 Mountain Hydrangea (desktop)
 pandoc   3.1.1 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)

quarto : "1.3.361"
````

### Quarto check output

````
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.361
      Path: C:\Users\lehuen201\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: C:/Python311/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.3.0
      Path: C:/Users/lehuen201/AppData/Local/Programs/R/R-4.3.0
      LibPaths:
        - C:/Users/lehuen201/AppData/Local/Programs/R/R-4.3.0/library
      knitr: 1.43
      rmarkdown: 2.22

[>] Checking Knitr engine render......OK
````

### PR DESCRIPTION
**Pull request by cderv**
and its comment character so options are parsed

closes https://github.com/quarto-dev/quarto-cli/issues/5994

@cscheid that would be the scoped way to handle a patch that does work no matter the knitr version. 

The issue is the same of all special engines so this include fix for mermaid. dot was working because already known by **knitr**

I believe this is safe to do that, and indeed is the right way to do it for current special engine implementation. 

Notice that OJS and mermaid / dot (`handledLanguages`) gets exactly the same treatment, but `ojs` is not part of `handledLanguages`, so we get two passes. I can refactor, but leaving this way makes it clear we do have different meaning for `ojs` and `mermaid` / `dot` (and possibly more later).

### CODE REVIEW

File: src/resources/rmd/patch.R [hunk 1]
```diff
@@ -268,3 +268,12 @@ valid_path = function(prefix, label) {
 }
 assignInNamespace("valid_path", valid_path, ns = "knitr")
 
+
+# add special language comment options support in knitr
+if (knitr_has_yaml_chunk_options()) {
+  knitr_comment_chars <- knitr:::comment_chars
+  knitr_comment_chars$ojs <- "//"
+  knitr_comment_chars$mermaid <- "%%"
```
Comment (yihui) [inline src/resources/rmd/patch.R:276]: FYI I just added them to **knitr**: https://github.com/yihui/knitr/commit/3dcfac4780accc3791855b298a556297f62dc73d

**Review by cscheid — APPROVED** [review]
Thank you! That looks great to me.

**Comment by cscheid** [comment]
We might want to add an entry to the changelog as well.

File: src/resources/rmd/patch.R (hunk 1 above)
Comment (cderv) [reply src/resources/rmd/patch.R:279]: Answered fast. Just realizing why I really did the patched in Quarto. 

Based on what we see in https://github.com/quarto-dev/quarto-cli/pull/7804 is that doing this in **knitr** means that `yaml.code` option now contains the options and not just `code`

I fixed that part in the PR here:
https://github.com/quarto-dev/quarto-cli/blob/f9ed45429ca157e055210c9c1ff7df10e4850f2e/src/resources/rmd/execute.R#L55-L62

but this means new knitr 1.46 will have impact (potential breakage) with Quarto 1.3. 

That is the probem with making change in **knitr** and potential impact on Quarto version 🤷‍♂️

Comment (yihui) [reply src/resources/rmd/patch.R:279]: Okay, it's clear to me now. Thanks for the explanation!

Comment (yihui) [reply src/resources/rmd/patch.R:279]: https://github.com/yihui/knitr/commit/b037a31888b101af00e4988a1444cadc31456587 should avoid the breakage. It also means this #7799 fix would be unnecessary, unless the next Quarto release is scheduled to be earlier than the next **knitr** release. The next version of **knitr** will be released relatively soon (perhaps in the next week or two).

Comment (cderv) [reply src/resources/rmd/patch.R:279]: > It also means this https://github.com/quarto-dev/quarto-cli/pull/7799 fix would be unnecessary,

I believe the fix would make Quarto 1.4 works with older **knitr**, and your fix in **knitr** insure that newer knitr also work correctly. 

If I revert #7799, it would mean that a **knitr** update is required by the user, but this could be considered too. 

@cscheid thoughts ?
