### PR TITLE
fix `mdx-code-block` special code block for docusaurus

### LINKED ISSUE #8333: [Docusaurus] `{=mdx}` code block seems broken (Quarto 1.4 with Docusaurus v3)
### Bug description

~~If we use mdx in mdx files, it doesn't seem necessary to write it as code blocks.~~

` ``` mdx-code-block` should be changed to ` ```mdx-code-block`

### Steps to reproduce

````qmd
---
title: foo
format: docusaurus-md
---

```{=mdx}
export const Highlight = ({children, color}) => (
  <span
    style={{
      backgroundColor: color,
      borderRadius: '2px',
      color: '#fff',
      padding: '0.2rem',
    }}>
    {children}
  </span>
);

<Highlight color="#25c2a0">Docusaurus GREEN</Highlight> and <Highlight color="#1877F2">Rams blue</Highlight> are my favorite colors.

I can write **Markdown** alongside my _JSX_!
```
````

### Expected behavior

````mdx
---
title: foo
format: docusaurus-md
---



```mdx-code-block
export const Highlight = ({children, color}) => (
  <span
    style={{
      backgroundColor: color,
      borderRadius: '2px',
      color: '#fff',
      padding: '0.2rem',
    }}>
    {children}
  </span>
);

<Highlight color="#25c2a0">Docusaurus GREEN</Highlight> and <Highlight color="#1877F2">Rams blue</Highlight> are my favorite colors.

I can write **Markdown** alongside my _JSX_!
```
````

### Actual behavior

````mdx
---
title: foo
format: docusaurus-md
---




``` mdx-code-block
export const Highlight = ({children, color}) => (
  <span
    style={{
      backgroundColor: color,
      borderRadius: '2px',
      color: '#fff',
      padding: '0.2rem',
    }}>
    {children}
  </span>
);

<Highlight color="#25c2a0">Docusaurus GREEN</Highlight> and <Highlight color="#1877F2">Rams blue</Highlight> are my favorite colors.

I can write **Markdown** alongside my _JSX_!
```
````

### Your environment

- Ubuntu 22.04

### Quarto check output

```sh
$ quarto check   
Quarto 1.4.545
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.545
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/local/python/current/bin/python3
      Jupyter: 5.7.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /usr/local/lib/R
      LibPaths:
        - /workspaces/querying-with-prql/renv/library/R-4.3/x86_64-pc-linux-gnu
        - /usr/local/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

### PR DESCRIPTION
**Pull request by cderv**
It is not handled by docusaurus if there is whitespace after backtick like pandoc is creating from CodeBlock

This fixes #8333 

Though from discussion there, it could also be an issue in docusaurus itself that they should fix as it is breaking from V2 to V3 
and it does not seem they mention this change as known  (cc @eitsupi) 

Their checker (https://github.com/slorber/docusaurus-mdx-checker) does not warn on the produced file with a space also 

So opening as draft to keep this if we decide to merge it

### CODE REVIEW

File: src/resources/extensions/quarto/docusaurus/docusaurus.lua [hunk 1]
```diff
@@ -53,7 +53,8 @@ end
 -- into raw commamark to pass through via dangerouslySetInnerHTML
 local function RawBlock(el)
   if el.format == 'mdx' then
-    return pandoc.CodeBlock(el.text, pandoc.Attr("", {"mdx-code-block"}))
+    -- special mdx-code-block is not handled if whitespace is present after backtrick (#8333)
+    return pandoc.RawBlock("markdown", "````mdx-code-block\n" .. el.text .. "\n````")
```
Comment (cscheid) [inline src/resources/extensions/quarto/docusaurus/docusaurus.lua:57]: This will break if `el.text` has a line starting with four backticks, right?

Comment (cderv) [reply src/resources/extensions/quarto/docusaurus/docusaurus.lua:57]: Yes, but `mdx-code-block` for docusaurus is based on a regex which handles 3 or 4 bacticks.

So 5 backticks for `mdx-code-block` won't work for a .mdx document. 

Based on comment at https://github.com/quarto-dev/quarto-cli/issues/8333#issuecomment-1898410942

https://github.com/facebook/docusaurus/blob/604ccaa89c46dd2e3b515e1beeefa52454447650/packages/docusaurus-utils/src/markdownUtils.ts#L70-L75

````ts
export function unwrapMdxCodeBlocks(content: string): string {
  // We only support 3/4 backticks on purpose, should be good enough
  const regexp3 =
    /(?<begin>^|\n)```mdx-code-block\n(?<children>.*?)\n```(?<end>\n|$)/gs;
  const regexp4 =
    /(?<begin>^|\n)````mdx-code-block\n(?<children>.*?)\n````(?<end>\n|$)/gs;
````

So this is best effort - at the end, this is poor handling on docusaurus side. 

Otherwise, we should not emid `mdx-code-block` by default as it does not seem needed, except on really specific case for some website. And maybe we could find a way to opt-in for a user who needs it.

Comment (cscheid) [reply src/resources/extensions/quarto/docusaurus/docusaurus.lua:57]: Software was a mistake.

**Comment by cscheid** [comment]
I think we need to merge this because we're providing the translation of blocks like this into `mdx-code-block` blocks as a feature:

````
```{=mdx}
...
```
````

We don't want Quarto to regress regress here, independently of how brittle Docusaurus is on this respect.

**Comment by cderv** [comment]
I agree, that is why I open the PR. I'll undraft and let you merge if we go for it for 1.4

I did not add a new tst by the way, but just adapted the existing one.
