### PR TITLE
Sort keys when encoding tables as JSON

### LINKED ISSUE #11122: GLightbox options cause HTML output to change
### Bug description

Order of GLightbox options changes on (almost) every HTML rendering. This may sound like a minor cosmetic detail but it causes the checksum of the output file to change and therefore makes caching more difficult.

### Steps to reproduce

Use any document containing an image, e.g.

```qmd
---
title: "Empty"
format: html
engine: jupyter
---

![An image]()
```

run the following commands:

```shell
quarto render --to html --output-dir output1
quarto render --to html --output-dir output2  # you may need to run this step more than once
diff output1/index.html output2/index.html
```

### Expected behavior

Output does not differ because input has not changed.

### Actual behavior

Order of GLightbox options is changed, e.g.

```diff
515c515
< <script>var lightboxQuarto = GLightbox({"selector":".lightbox","descPosition":"bottom","loop":false,"closeEffect":"zoom","openEffect":"zoom"});
---
> <script>var lightboxQuarto = GLightbox({"loop":false,"selector":".lightbox","openEffect":"zoom","descPosition":"bottom","closeEffect":"zoom"});
```

### Your environment

nixos-version: 24.05.20241012.a3f9ad6 (Uakari)

### Quarto check output

<details>
<summary>quarto check</summary>

```
Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      commit: 71945532e1fc1a5cf113117f6d5ff5bee3991797
      Path: ~/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /run/current-system/sw/bin
      Version: undefined

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.5
      Path: ~/quarto-playground/.venv/bin/python3
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```
</details>

### PR DESCRIPTION
**Pull request by winniehell**
## Description

Sorts object keys when encoding a table as JSON. This makes JSON objects deterministic which is especially useful for the GLightbox parameters which are part of the rendered HTML. This change may have unintended side effects such as performance degradation which I hope will be revealed by a review.

closes https://github.com/quarto-dev/quarto-cli/issues/11122

## Checklist

I have (if applicable):

- [x] filed a [contributor agreement](https://github.com/quarto-dev/quarto-cli/blob/main/CONTRIBUTING.md).
- [x] referenced the GitHub issue this PR closes
- [x] updated the appropriate changelog

### CODE REVIEW

**Comment by winniehell** [comment]
I verified locally that this change resolves https://github.com/quarto-dev/quarto-cli/issues/11122 but of course it has larger impact on the code base which I'm not sure is wanted.

I will still send in the contributor agreement later.

**Comment by cscheid** [comment]
Thanks for the PR. The fix makes sense, but `json.lua` is an upstream dependency, see the [header](https://github.com/quarto-dev/quarto-cli/pull/11124/files#diff-4119ff37fe985fddcc6bf731212d9406032c9177300ea25ecd38339bf30de825R5):

```lua
--
-- json.lua
--
-- Copyright (c) 2020 rxi
-- https://github.com/rxi/json.lua
--
```

I have a slight preference towards making a fix upstream first.

**Comment by winniehell** [comment]
@cscheid I can try but that library has not seen any activity in the last four years, so I'm not optimistic it will get merged any time soon.

**Comment by cscheid** [comment]
I'd be more willing to take a PR here if the fix were mergeable upstream first. Your fix creates a dependency between json.lua and Quarto, and that's not really wanted in this context.

**Comment by winniehell** [comment]
yep, I understand. :+1: the alternative however implies that `sortedPairs` is duplicated upstream which leads to at least two copies in Quarto. There are already multiple anyway so this may not be a big deal.

**Comment by cscheid** [comment]
We're not a go shop but the [appropriate proverb](https://go-proverbs.github.io/) applies here: [A little copying is better than a little dependency.](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=9m28s)

**Comment by winniehell** [comment]
We are in agreement here and for this situation and I also dislike big dependency trees. But I have also made bad experience with legacy code bases that had a lot of duplication and some of the duplicates were adjusted to behave slightly different. So there is probably a sweet spot somewhere in the middle (and just to be absolutely clear: I'm not suggesting any change in strategy for Quarto here, just sharing my point of view).

**Comment by winniehell** [comment]
upstream pull request: https://github.com/rxi/json.lua/pull/51

**Comment by winniehell** [comment]
@cscheid yep, I have also included the other unreleased changes from upstream and created a pull request for your earlier changes: https://github.com/rxi/json.lua/pull/52

File: src/resources/pandoc/datadir/_json.lua [hunk 1]
```diff
@@ -101,13 +116,13 @@ local function encode_table(val, stack)
...
     -- Treat as object
-    for k, v in pairs(val) do
+    for k, v in pairsByKeys(val) do
       table.insert(res, encode_string(k) .. ":" .. encode(v, stack))
     end
     stack[val] = nil
     return "{" .. table.concat(res, ",") .. "}"
   else
-    return "[]"
+    error( string.format("invalid table: unsupported key type %s", types[1]) )
```
Comment (winniehell) [inline src/resources/pandoc/datadir/_json.lua:125]: change in functionality to maintain compatibility with upstream tests, encoding `{ [ function() end ] = 12 }` in particular

File: src/resources/pandoc/datadir/_json.lua [hunk 2]
```diff
@@ -26,7 +27,22 @@
 -- SOFTWARE.
 --
 
-local json = { _version = "0.1.2" }
+local json = { _version = "0.1.2-quarto" }
```
Comment (winniehell) [inline src/resources/pandoc/datadir/_json.lua:30]: we can't keep the version number but I'm not sure if this is a good way to deal with it

File: src/resources/pandoc/datadir/_json.lua [hunk 3]
```diff
@@ -72,7 +88,6 @@ local function encode_table(val, stack)
 
   stack[val] = true
 
-  local n = 0
```
Comment (winniehell) [inline src/resources/pandoc/datadir/_json.lua:75]: unused

File: src/resources/pandoc/datadir/_json.lua (hunk 1 above)
Comment (winniehell) [reply src/resources/pandoc/datadir/_json.lua:125]: that change broke encoding empty tables which is not covered by upstream tests. I will fix that.

Comment (winniehell) [reply src/resources/pandoc/datadir/_json.lua:129]: fixed upstream as well and also added tests there :heavy_check_mark:

File: src/resources/pandoc/datadir/_json.lua [hunk 4]
```diff
@@ -72,7 +88,10 @@ local function encode_table(val, stack)
...
+  if next(val) == nil then
+    return '[]'
```
Comment (winniehell) [inline src/resources/pandoc/datadir/_json.lua:92]: this is consistent with previous behavior but an empty table could also be encoded as `{}`

File: src/resources/pandoc/datadir/_json.lua (hunk 2 above)
Comment (cscheid) [reply src/resources/pandoc/datadir/_json.lua:30]: This is fine.

File: src/resources/pandoc/datadir/_json.lua (hunk 4 above)
Comment (cscheid) [reply src/resources/pandoc/datadir/_json.lua:92]: The correspondence between JSON's `{}`,`[]`, `null` and Lua's `{}` and `nil` can never be done perfectly, so we should just maintain the previous behavior.

**Review by cscheid — COMMENTED** [review]
This looks great, thank you.

We're still missing the changelog update, right?

File: news/changelog-1.6.md [hunk 5]
```diff
@@ -29,6 +30,7 @@ All changes included in 1.6:
 - Fix `kbd` element styling on dark themes.
 - ([#10761](https://github.com/quarto-dev/quarto-cli/issues/10761)): Add support for `licence: CC0` to automatically link to Creative Commons licence [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/).
 - ([#10817](https://github.com/quarto-dev/quarto-cli/issues/10817)): Ensure that user provided SCSS has precedent over quarto generated scss also for dark theme.
+- ([#11124](https://github.com/quarto-dev/quarto-cli/pull/11124)): Use stable order of GLightbox options
```
Comment (winniehell) [inline news/changelog-1.6.md:33]: I have added two entries because I think there are two aspects of this change: one refactoring which may have unsurfaced side effects and one bugfix / enhancement. please feel free to delete either of them.

Comment (cscheid) [reply news/changelog-1.6.md:33]: Ok. I'll remove the `html` format change.

Comment (winniehell) [reply news/changelog-1.6.md:33]: most users will probably not notice this anyway :sweat_smile:

**Comment by cscheid** [comment]
Merged - thanks for the PR and followup!
