### PR TITLE
Unneeded matching pages call triggers throttling on some large Confluence projects. #4548

### LINKED ISSUE #4548: Unneeded matching pages call triggers throttling on some large Confluence projects.
STR

- Attempt to publish [Quarto Web](https://github.com/quarto-dev/quarto-web/tree/task/test-confluence)

Expected:  Publishes without error

Actual:  Sometimes we receive from Confluence a  `REFUSED_STREAM` `stream error received: refused stream before processing any application logic`

https://httpwg.org/specs/rfc9113.html#REFUSED_STREAM
https://httpwg.org/specs/rfc9113.html#Reliability

````
ERROR: TypeError: error sending request for url 

(https://rstudiopbc-sandbox-249.atlassian.net/wiki/rest/api/content/search?cql=title=%22Docs%2Fpresentations%2Frevealjs%2Fdemo%2Fmini%2Fzoom%22&spaces=QTCT&cqlcontext=%7B%22contentStatuses%22%3A%5B%22archived%22%2C%20%22current%22%2C%20%22draft%22%5D%7D):

 http2 error: stream error received: refused stream before processing any application logic
````

We should try a simple one-time retry in this case.  We can consider a more complex retry strategy if this is a common problem.

### PR DESCRIPTION
**Pull request by ghost**
#fixes #4548

### CODE REVIEW

File: src/publish/confluence/api/types.ts [hunk 1]
```diff
@@ -188,7 +188,6 @@ export type SiteFileMetadata = {
   fileName: string;
   title: string;
   originalTitle: string;
-  matchingPages: ContentSummary[];
```
Comment (allenmanning) [inline src/publish/confluence/api/types.ts:191]: Dead 💀 and was causing throttling as it was spamming with `Promise.all`.

File: src/publish/confluence/confluence.ts [hunk 2]
```diff
@@ -650,16 +650,10 @@ async function publish(
       const originalTitle = getTitle(fileName, metadataByInput);
       const title = originalTitle;
 
-      const matchingPages = await client.fetchMatchingTitlePages(
```
Comment (allenmanning) [inline src/publish/confluence/confluence.ts:653]: Dead 💀 and was causing throttling as it was spamming with `Promise.all`.
