### PR TITLE
floatref - avoid caption duplication on Div Crossref with captioned Markdown table 

### LINKED ISSUE #13051: Duplicated captions in Quarto 1.8.16, 1, 1.7.32. Ok in 1.5.8
### I have:

- [x] searched the issue tracker for similar issues
- [x] installed the latest version of [Quarto CLI](https://github.com/quarto-dev/quarto-cli/releases/latest)
- [ ] formatted my issue following the [Bug Reports guide](https://quarto.org/bug-reports.html)

### Bug description

A table caption is duplicated when using Table numbering.

### Steps to reproduce

````
---
title: "testcaption"
---

## Duplicate captions


```{r}
#| tab-cap: "My caption could run over several lines, if the world is round"
#| label: tbl-my_cap

knitr::kable(iris[1:6,])
```

````

### Actual behavior

With Quarto 1.8.16, 1, 1.7.6, 1.7.32  (others not tested) output is: 

```
Table 1: My caption could run over several lines, if the world is round
My caption could run over several lines, if the world is round
< follows table>
```

### Expected behavior

Quarto 1.5.8 produces correct output

```
Table 1: My caption could run over several lines, if the world is round
< follows table>
```

### Your environment

RStudio 2024.12.1 Build 563
Windows 11

### Quarto check output

Several releases were tested; see above. 

[testcaption.zip](https://github.com/user-attachments/files/21156756/testcaption.zip)

### PR DESCRIPTION
**Pull request by cderv**
closes #13051 

when caption is taken on the table element, remove it from the table

this is because Quarto floatref processes the table caption and it needs to be removed from the table element so that it doesn't get inserted twice

This happens with syntax like 

````markdown
## Using `:` syntax

::: {#tbl-1}

| Default | Left | Right | Center |
|---------|:-----|------:|:------:|
| 12      | 12   |    12 |   12   |
| 123     | 123  |   123 |  123   |
| 1       | 1    |     1 |   1    |

: This is the caption for the table 1

:::

See @tbl-1

## Using `Table:` syntax

::: {#tbl-2}

| Default | Left | Right | Center |
|---------|:-----|------:|:------:|
| 12      | 12   |    12 |   12   |
| 123     | 123  |   123 |  123   |
| 1       | 1    |     1 |   1    |

Table: This is the caption for the table 2

:::

See @tbl-2
````

This PR adds also 

- Regression for this specific duplication
- More supported syntax in ff-matrix with test

> [!NOTE]
> The fix is a candidate for a backport as it was a regression in 1.7 from https://github.com/quarto-dev/quarto-cli/commit/8bec5e35f6a677a4ad41318a2b125f1204dec2da 
> I'll do a PR once validated

### CODE REVIEW

File: src/resources/filters/quarto-pre/parsefiguredivs.lua [hunk 1]
```diff
@@ -267,6 +267,8 @@ function parse_floatreftargets()
           if table.caption.long and next(table.caption.long) then
             found_caption = true
             caption = table.caption.long[1] -- what if there's more than one entry here?
+            -- table caption should be removed from the table as we'll handle it
+            table.caption.long = pandoc.Blocks({})
```
Comment (cderv) [inline src/resources/filters/quarto-pre/parsefiguredivs.lua]: @tarleb in 
- https://github.com/quarto-dev/quarto-cli/pull/11525

There was suppression of the caption removal: https://github.com/quarto-dev/quarto-cli/commit/8bec5e35f6a677a4ad41318a2b125f1204dec2da

it was `tbl.caption.long = nil` which seemed to be incorrect. 

Is setting to empty block the more efficient way to remove the `table.caption`?

This is what we want to do here. Thanks

Comment (tarleb) [reply src/resources/filters/quarto-pre/parsefiguredivs.lua]: Pandoc 3.6.1 added a `pandoc.Caption` constructor, so the cleanest variant would probably be

``` lua
table.caption = pandoc.Caption{}
```

This would also make sure that the short caption is reset. The short caption is intended to be used in the List of Tables, but it's not set in the default Markdown reader. But if that ever changes, then we capture that case as well.

Comment (cderv) [reply src/resources/filters/quarto-pre/parsefiguredivs.lua]: Thanks, I missed that. Changed done. 

> The short caption is intended to be used in the List of Tables

I wonder how we support that in Quarto. This would interesting support.

**Comment by cscheid** [comment]
This is a good improvement, but I don't think it's a bug, and so we don't need the hotfix. My understanding is that the Div syntax has always required a content element and a caption element. If it worked before it was an accident; we never promised it would work.

**Comment by cderv** [comment]
> My understanding is that the Div syntax has always required a content element and a caption element. If it worked before it was an accident; we never promised it would work.

I assumed from this code in 1.6 that we were supposed to support it
https://github.com/quarto-dev/quarto-cli/blob/5fc64f616333b3e44d0199b57edd6d9b3d2a8e83/src/resources/filters/quarto-pre/parsefiguredivs.lua#L237-L269

As you can see, the logic is 

* Look for caption inside the Div
  https://github.com/quarto-dev/quarto-cli/blob/5fc64f616333b3e44d0199b57edd6d9b3d2a8e83/src/resources/filters/quarto-pre/parsefiguredivs.lua#L237-L238

* If not found, then look as attribute on the Div
  https://github.com/quarto-dev/quarto-cli/blob/5fc64f616333b3e44d0199b57edd6d9b3d2a8e83/src/resources/filters/quarto-pre/parsefiguredivs.lua#L240

* If not found, look at the caption on the Table itself
  https://github.com/quarto-dev/quarto-cli/blob/5fc64f616333b3e44d0199b57edd6d9b3d2a8e83/src/resources/filters/quarto-pre/parsefiguredivs.lua#L243-L256

So it was not document in our website, but it was working from this code base. 

We had a caption removal at
https://github.com/quarto-dev/quarto-cli/blob/5fc64f616333b3e44d0199b57edd6d9b3d2a8e83/src/resources/filters/quarto-pre/parsefiguredivs.lua#L252

which was removed accidentaly in https://github.com/quarto-dev/quarto-cli/commit/8bec5e35f6a677a4ad41318a2b125f1204dec2da

So, based on Codebase this was working. 

I am fine to not do the backport, but it seemed a good candidate based on this history.
