### PR TITLE
lua - fix constant references

### LINKED ISSUE #8507: Docx callouts appearance broken in 1.4
The following document renders poorly in Quarto 1.4:

```markdown
---
title: Hello World
author: Charles Teague
format: docx
---

## A simple callout

:::{.callout-note}

What up dog?

:::
```

## Results:

| v1.3 | v1.4 |
| --- | --- |
|  |  |

### PR DESCRIPTION
**Pull request by cscheid**
Closes #8507.

### CODE REVIEW

File: src/resources/filters/quarto-post/docx.lua [hunk 1]
```diff
@@ -193,7 +197,8 @@ function calloutDocx(node)
   local appearance = node.appearance
   local hasIcon = node.icon 
 
-  if appearance == kCalloutAppearanceDefault then
+  print(appearance, constants.kCalloutAppearanceDefault)
```
Comment (cscheid) [inline src/resources/filters/quarto-post/docx.lua:200]: Oops - I'll fix this before merging. Just letting the tests run.
