### PR TITLE
fix: Microsoft Edge not detected (Quarto 1.6.4) on macOS

### LINKED ISSUE #10464: Microsoft Edge not detected (Quarto 1.6.4)
### Bug description

I've removed chromium from my MacBook (and Mac Mini). After a restart, Quarto 1.6.4 complains that no chromium was detected and does not use Microsoft Edge which is installed. Reference: #10172

### Steps to reproduce

Take the example from the original post (#10162):

````
---
title: "In-Class: Relations - Digraphs"
format: 
  pdf: default
---

Any quarto document that includes a diagram and compiling a PDF; here's a sample:


```{dot}
//| fig-width: 2
digraph {
  node [shape = circle, width=0.5];
  rankdir = LR;
  1 -> 1;
  1 -> 2;
  2 -> 4; 
  1 -> 3;
  3 -> 4;
  4 -> 1;
}

```
````

### Expected behavior

Edge should be used if chromium is not installed

### Actual behavior

Error message:

ERROR: Chrome not found

No Chrome or Chromium installation was detected.

Please run 'quarto install chromium' to install Chromium.

### Your environment

- IDE: n/a
- macOS: 14.6 (23G80) as well as 15.1 Beta (24B5009l)

### Quarto check output

````bash
Quarto 1.6.4
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.4
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.2
      Path: /Users/USER/.pyenv/versions/3.10.2/bin/python3
      Jupyter: 5.3.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.48
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK

````

### PR DESCRIPTION
**Pull request by mcanouil**
Fix the TypeScript checking for path of chrome/chromium.

Fixes #10464

This is a follow up PR of:
- #10172

### CODE REVIEW

File: src/core/puppeteer.ts [hunk 1]
```diff
@@ -206,9 +206,7 @@ async function findChrome(): Promise<string | undefined> {
       "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
       "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
     ];
-    return programs.find((p) => {
-      safeExistsSync(p);
-    });
+    return programs.find(safeExistsSync);
```
Comment (cscheid) [inline src/core/puppeteer.ts:209]: Why should this make a difference?

The transformation of `f` to `(parameter) => f(parameter)` makes a difference when functions take more than one parameter (so that eg `find` doesn't accidentally pass a stray parameter). But `safeExistsSync` is:

https://github.com/quarto-dev/quarto-cli/blob/a90f4b0040229318e343946323d601075edcb452/src/core/path.ts#L112-L118

That takes a single parameter. So I don't understand this.

Comment (mcanouil) [reply src/core/puppeteer.ts:209]: I don't either but for some reason the previous code does not detect/return the path when it exists and the one here does.
I am no TypeScript expert.

Comment (mcanouil) [reply src/core/puppeteer.ts:209]: The current code returns undefined.
I even try adding Brave in the array to test one more browser.
Only the proposed code/syntax returns the correct path.

Comment (gordonwoodhull) [reply src/core/puppeteer.ts:209]: Correct me if I'm wrong but doesn't

```ts
    return programs.find((p) => {
      safeExistsSync(p);
    });
```
always fail,  because it should either have `return` or no braces? Functions return `undefined` by default. 

I.e. this is *not* the same as 

> `(parameter) => f(parameter)`

Comment (cscheid) [reply src/core/puppeteer.ts:209]: Ah, that's _exactly_ what it is, Gordon. I always get confused by fat arrow syntax with braces.

More specifically

```js
(p) => { safeExistsSync(p); }
```

is _very different_ from

```js
(p) => safeExistsSync(p); // which _is_ equivalent to safeExistsSync
```

Ok, this all makes sense now, except that I don't really understand why TypeScript let us write the obviously-broken function before!

Comment (mcanouil) [reply src/core/puppeteer.ts:209]: I learned something. Thanks @gordonwoodhull

Comment (cderv) [reply src/core/puppeteer.ts:209]: Oh thanks ! I believe my mistake 😓 good catch @mcanouil ! 

I will remember the difference now... Though I get mixed up by R syntax so it could happen again 😅

Comment (mcanouil) [reply src/core/puppeteer.ts:209]: You did say you did not test macOS on the initial PR. And I believe to know this, you need to be bitten by it first^^
