### PR TITLE
title is not always present, handle accordingly

### LINKED ISSUE #5079: Docusaurus format of 1.3 rc seems broken
### Bug description

I tried the Docusaurus format with Quarto 1.3 and noticed that quite a few features are no longer working.

- `code-fold: true` does not work
- YAML front matter is not output to .md files
- If a call out block is included, rendering will fail

I tested with quarto cli 1.3.306 and create-docusaurus@2.4.0 on Linux (Debian or Ubuntu)

```sh
$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.306
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.2
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

I get an error when I add the following qmd file to the Docusaurus sample project and run `quarto preview`.

````qmd
---
title: foo
---

:::{.callout-note}

This is callout

:::
````

```sh
$ quarto preview
Preparing to preview
[1/1] docs/test.qmd
Error running filter /opt/quarto/share/filters/main.lua:
Inline, list of Inlines, or string expected, got nil
        while retrieving function argument content
        while retrieving arguments for function Header
stack traceback:
        ...share/extensions/quarto/docusaurus/docusaurus_writer.lua:73: in function <...share/extensions/quarto/docusaurus/docusaurus_writer.lua:70>
        (...tail calls...)
        /opt/quarto/share/filters/main.lua:71: in function </opt/quarto/share/filters/main.lua:70>
        (...tail calls...)
        [C]: in ?
        [C]: in method 'walk'
        /opt/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
        ...share/extensions/quarto/docusaurus/docusaurus_writer.lua:49: in field 'handle'
        /opt/quarto/share/filters/main.lua:742: in function </opt/quarto/share/filters/main.lua:739>
        [C]: in ?
        [C]: in method 'walk'
        /opt/quarto/share/filters/main.lua:4116: in function </opt/quarto/share/filters/main.lua:4114>
        [C]: in ?
        [C]: in method 'walk'
        /opt/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
        /opt/quarto/share/filters/main.lua:449: in local 'callback'
        /opt/quarto/share/filters/main.lua:454: in upvalue 'run_emulated_filter_chain'
        /opt/quarto/share/filters/main.lua:495: in function </opt/quarto/share/filters/main.lua:476>
stack traceback:
        /opt/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
        ...share/extensions/quarto/docusaurus/docusaurus_writer.lua:49: in field 'handle'
        /opt/quarto/share/filters/main.lua:742: in function </opt/quarto/share/filters/main.lua:739>
        [C]: in ?
        [C]: in method 'walk'
        /opt/quarto/share/filters/main.lua:4116: in function </opt/quarto/share/filters/main.lua:4114>
        [C]: in ?
        [C]: in method 'walk'
        /opt/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
        /opt/quarto/share/filters/main.lua:449: in local 'callback'
        /opt/quarto/share/filters/main.lua:454: in upvalue 'run_emulated_filter_chain'
        /opt/quarto/share/filters/main.lua:495: in function </opt/quarto/share/filters/main.lua:476>
stack traceback:
        /opt/quarto/share/filters/main.lua:4116: in function </opt/quarto/share/filters/main.lua:4114>
        [C]: in ?
        [C]: in method 'walk'
        /opt/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
        /opt/quarto/share/filters/main.lua:449: in local 'callback'
        /opt/quarto/share/filters/main.lua:454: in upvalue 'run_emulated_filter_chain'
        /opt/quarto/share/filters/main.lua:495: in function </opt/quarto/share/filters/main.lua:476>
stack traceback:
        /opt/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
        /opt/quarto/share/filters/main.lua:449: in local 'callback'
        /opt/quarto/share/filters/main.lua:454: in upvalue 'run_emulated_filter_chain'
        /opt/quarto/share/filters/main.lua:495: in function </opt/quarto/share/filters/main.lua:476>
```

The following qmd files are converted to an empty md file.

```qmd
---
title: foo
---
```

I think this is a serious regression and I recommend adding Docusaurus format tests to this repository. (Docusaurus integration is really great!)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

### PR DESCRIPTION
**Pull request by cscheid**
This fixes a bug on the docusaurus writer where if a callout has no title, render will fail.

This closes #5079.

### CODE REVIEW

File: src/resources/extensions/quarto/docusaurus/docusaurus_writer.lua [hunk 1]
```diff
@@ -70,10 +70,12 @@ function Writer(doc, opts)
     Callout = function(node)
       local admonition = pandoc.List()
       admonition:insert(pandoc.RawBlock("markdown", ":::" .. node.type))
-      admonition:insert(pandoc.Header(2, node.title))
+      if node.title then
```
Comment (allenmanning) [inline src/resources/extensions/quarto/docusaurus/docusaurus_writer.lua:73]: Is testing coverage a good idea here to protect us from potential future regressions?

Comment (cscheid) [reply src/resources/extensions/quarto/docusaurus/docusaurus_writer.lua:73]: It would add an additional setup requirement to our test suite, setting up npm, npx, and docusaurus.

We could do it, but I'd like to have a longer discussion first.

Comment (eitsupi) [reply src/resources/extensions/quarto/docusaurus/docusaurus_writer.lua:73]: Is it possible to have quarto only execution without running the npm command for testing? (This may require additional functionality.)

File: src/command/render/output.ts [hunk 2]
```diff
@@ -129,7 +133,8 @@ export function outputRecipe(
     }
 
     // complete hook for keep-yaml
-    if (recipe.keepYaml) {
+    // workaround for https://github.com/quarto-dev/quarto-cli/issues/5079
+    if (recipe.keepYaml || recipe.format.render[kPreserveYaml]) {
```
Comment (cderv) [inline src/command/render/output.ts:137]: Regarding `preserve-yaml` addition, I believe we are round-tripping here. 

As discussed already in https://github.com/quarto-dev/quarto-cli/issues/4210, Tehre was a `keep-yaml` option, which was removed in 1.2 (detail here: https://github.com/quarto-dev/quarto-cli/issues/4210#issuecomment-1452185273)

The YAML preservation should be done by using the Pandoc's extension  `+yaml_metadata_block`
Adding this variant to the format extension should be enough. Did you try that already ?

I  am trying to keep things clear here and helping identify the correct fix.

File: src/resources/extensions/quarto/docusaurus/_extension.yml [hunk 3]
```diff
@@ -17,9 +17,13 @@ contributes:
     format: docusaurus-md
   formats:
     md:
+      # Although we use a custom writer, we still need the variants here the lua filters to render correctly.
+      # Ideally, we would forward the variants to the custom writer.
+      variant: gfm+pipe_tables+tex_math_dollars+header_attributes+raw_html+all_symbols_escapable+backtick_code_blocks+fenced_code_blocks+space_in_atx_header+intraword_underscores+lists_without_preceding_blankline+shortcut_reference_links
       writer: docusaurus_writer.lua
       output-ext: md
       inline-includes: true
+      preserve-yaml: true
```
Comment (cderv) [inline src/resources/extensions/quarto/docusaurus/_extension.yml:26]: Going with my other comment I believe adding the variant shoudl work 

```suggestion
      # Although we use a custom writer, we still need the variants here the lua filters to render correctly.
      # Ideally, we would forward the variants to the custom writer.
      variant: gfm+pipe_tables+tex_math_dollars+header_attributes+raw_html+all_symbols_escapable+backtick_code_blocks+fenced_code_blocks+space_in_atx_header+intraword_underscores+lists_without_preceding_blankline+shortcut_reference_links+yaml_metadata_block
      writer: docusaurus_writer.lua
      output-ext: md
      inline-includes: true
```

**Review by cderv — COMMENTED** [review]
Just a comment about the YAML preservation based on some other discussion in https://github.com/quarto-dev/quarto-cli/issues/4210 and history of the changes

File: src/resources/extensions/quarto/docusaurus/_extension.yml (hunk 3 above)
Comment (cscheid) [reply src/resources/extensions/quarto/docusaurus/_extension.yml:26]: This doesn't work because of a variety of reasons. JJ and I spent 40 minutes pairing over this. It's complicated :)

File: src/command/render/output.ts (hunk 2 above)
Comment (cscheid) [reply src/command/render/output.ts:137]: You're not correct, but it's easier to explain on Slack. Let me know there if you want the full story.

File: src/resources/extensions/quarto/docusaurus/_extension.yml (hunk 3 above)
Comment (cderv) [reply src/resources/extensions/quarto/docusaurus/_extension.yml:26]: Just wanted to be sure it was not forgotten ! All good then.

File: src/resources/extensions/quarto/docusaurus/docusaurus_writer.lua (hunk 1 above)
Comment (allenmanning) [reply src/resources/extensions/quarto/docusaurus/docusaurus_writer.lua:73]: It may be worth considering if we have seen and believe we will continue to see these types of regressions in the future.
