### PR TITLE
Fixup some knitr syntax in Lua to support SQL engine output 

### LINKED ISSUE #4869: Article Layout Margin option for knitr sql code block seems buggy
### Bug description

It seems that code blocks as well as the resulting table are placed in the margin.

- OS: Ubuntu 22.04
- Quarto Dev version (latest commit)

````qmd
---
title: test
format:
  html:
    self-contained: true
engine: knitr
---

```{r}
#| echo: false

library(DBI)
library(prqlr)
con <- dbConnect(RSQLite::SQLite(), ":memory:")
dbWriteTable(con, "mtcars", mtcars)
```

```{r, chunk-one}
#| column: margin
mtcars |>
  dplyr::select(cyl) |>
  head(5) |>
  knitr::kable()
```

```{sql}
#| column: margin
#| connection: con

select cyl from mtcars limit 5
```

```{r, chunk-one}
#| column: margin
```
````

Animation

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

### PR DESCRIPTION
**Pull request by cderv**
This closes #4869

I believe **knitr** SQL engine is not correctly designed, and this creates for us some difficulty to catch its output to wrap it under output `cell-output-display` div. The engine sets `results = 'asis'` and the output is only `cat()` without any other processing (no hooks, or no sewing of class item). `sew.character` is directly applied on it and not the `sew()` method that we do patch. 

Anyhow, i did not find any easy way to do the fixup in R without regex or else. It seemed fragile, and more robust to add a fixup stage in Lua. This is possible because a `div` is emitted and this is correctly parsed as `pandoc.Div` due to `native_spans` extension being the default. 

Other approach would be to consider this behavior in Quarto a bug in **knitr** and would require an update of the .sql engine for its output to go through the proper `sew()` processing, or have a `class` we can catch (we should catch a  `knit_asis` element but here it is missing). 

Doing this in **knitr** would require an update of **knitr** to be used with Quarto - this fix here should solve for any knitr version. 
This could be interesting in the meantime to have it, but if you think fixing this in **knitr** is better I can work on that too. 

@cscheid I added the step as an init step with a conditional on engine being used. My understanding is that this should happen from the start of AST normalization before any processing as we are fixing up the input syntax. If this needs to be elsewhere, please do tell me.

### CODE REVIEW

File: src/command/render/render.ts [hunk 1]
```diff
@@ -199,7 +199,11 @@ export async function renderPandoc(
   }
 
   // run pandoc conversion (exit on failure)
-  const pandocResult = await runPandoc(pandocOptions, executeResult.filters);
+  const pandocResult = await runPandoc(
+    pandocOptions,
+    executeResult.filters,
+    context.engine.name,
```
Comment (cscheid) [inline src/command/render/render.ts:205]: Everything else looks good, but I think we can improve this change here. Notice that pandocOptions already has `executionEngine` (see src/command/render/types.ts). We should use that one, right?

**Review by cscheid — COMMENTED** [review]
We should change the way runPandoc sends the engine name to Lua. But everything else looks good!

File: src/command/render/render.ts (hunk 1 above)
Comment (cderv) [reply src/command/render/render.ts:205]: > Notice that pandocOptions already has executionEngine (see src/command/render/types.ts). We should use that one, right?

😓 I looked for to see if it was already in, and missed this. This is definitely better to use it.
