### PR TITLE
Fix `embed` and `verbatim` knitr's engine for revealjs 

### LINKED ISSUE #4712: revealjs does not work with knitr embed engine
### Bug description

Using Quarto 1.2.335 (which is included in recent RStudio dailies, including 2023.03.0+385). This problem can be recreated without using the RStudio IDE when rendering using Quarto from the command-line.

Given a `code.R` file:

```r
cat("this is code.R\n")
```

The following revealjs document does not show the embedded code:

````markdown
---
title: embedding with reveal
format: revealjs
engine: knitr
---

## Embed!

```{embed, file = "code.R"}
```
````

image

The generated HTML contains a block, but no code:

```html
<section id="embed" class="slide level2">
<h2>Embed!</h2>
<div class="cell" data-file="code.R">

</div>
<div class="footer footer-default">

</div>
</section>
```

In contrast, when we do not output to HTML, the embedded code is shown.

````markdown
---
title: embedding without reveal
engine: knitr
---

## Embed!

```{embed, file = "code.R"}
```
````

image

Using the most recent version of knitr from CRAN and R 3.6.3 on macOS 12.6.3.

```bash
R -s -e "packageVersion('knitr')"
#> [1] ‘1.42’
```

Discovered while trying to apply the workaround from https://github.com/quarto-dev/quarto-cli/issues/1237

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

### PR DESCRIPTION
**Pull request by cderv**
General fix : With new `embed` feature in 1.3 for Jupyter, we need to make sure this does not override `embed` Knitr engine (cc @dragonstyle  as discussed)

Specific to revealjs: Set echo = TRUE for `embed` and `verbatim` engine when `revealjs` because those engine expect `echo` to be TRUE to be shown, but `revealjs` default to `FALSE`

This fix #4712

Note: our extension to include external file works fine - but it feels like those engines should still work correctly

By working on these R files, I think we can improve the handling of chunk hook, especially to treat those two engines as others (if we want to support `echo: fenced` for example. At first I did it in this PR, but then as this is some R refactoring more generic, I'll do it in another PR (#4735). We can then postpone to 1.4 if we think this is two much.

### CODE REVIEW

**Comment by cderv** [comment]
Following meeting and discussion with @cscheid this needs to be split as the `embed` override is in fact a more broader issue where non-cell handler should not be passed to **knitr** among `handledLanguages`

Currently all are 

``` r
names(knitr::knit_engines$get())
```

     [1] "awk"       "bash"      "coffee"    "gawk"      "groovy"    "haskell"  
     [7] "lein"      "mysql"     "node"      "octave"    "perl"      "php"      
    [13] "psql"      "Rscript"   "ruby"      "sas"       "scala"     "sed"      
    [19] "sh"        "stata"     "zsh"       "asis"      "asy"       "block"    
    [25] "block2"    "bslib"     "c"         "cat"       "cc"        "comment"  
    [31] "css"       "ditaa"     "dot"       "embed"     "eviews"    "exec"     
    [37] "fortran"   "fortran95" "go"        "highlight" "js"        "julia"    
    [43] "python"    "R"         "Rcpp"      "sass"      "scss"      "sql"      
    [49] "stan"      "targets"   "tikz"      "verbatim"  "ojs"       "mermaid"  
    [55] "include"  

Meaning `include`  is also pass (see the end)  - `embed` is there as an override of the built-in one, like `dot` handler from Quarto which overrides the **knitr** one, but I think that is fine in the context of Quarto. 

So we need first another PR for the handler adaptation

File: src/core/handlers/base.ts [hunk 1]
```diff
@@ -279,8 +279,15 @@ function makeHandlerContext(
...
 export function languages(): string[] {
-  return Object.keys(handlers);
+  const cellLanguage = [];
+  for (const [k, v] of Object.entries(handlers)) {
+    if (v.type === "cell") {
+      cellLanguage.push(k);
+    }
+  }
+  return cellLanguage;
 }
```
Comment (cderv) [inline src/core/handlers/base.ts:291]: @cscheid this is my proposal for the language cell issue. My understanding is that `languages()` should return only cell type handler and not others. We are using `languages()` in several places in the code, but it seems that this is what is expected. Also considering your work on https://github.com/quarto-dev/quarto-cli/commit/7c215a56e50f83d943fb35dbaa109d4374492d4f

File: src/resources/rmd/hooks.R [hunk 2]
```diff
@@ -44,6 +44,15 @@ knitr_hooks <- function(format, resourceDir, handledLanguages) {
...
     }
+    # handle specifically format which sets echo: false like revealjs
+    if (knitr::pandoc_to("revealjs", exact = TRUE)) {
+      # to adapt to true for engine that have no output
+      if (identical(options[["echo"]], FALSE) &&
+          options[["engine"]] %in% c("embed", "verbatim")
+      ) {
+        options[["echo"]] <- TRUE
+      }
+    }
```
Comment (cderv) [inline src/resources/rmd/hooks.R:55]: This is the proposal to have `echo: true` in revealjs by default for some engines. **revealjs** defaults to `echo: true` so using those engine requires to know that setting `echo: true` on chunk is needed. 

````markdown

```{embed}
#| echo: true
#| file: code.R
```
````

Otherwise, it does not show as explained in the issue. 

Maybe it is too much... would like your thought on that ? 
Other solution would be to document this (maybe in https://quarto.org/docs/presentations/revealjs/#code-echo)

Comment (jjallaire) [reply src/resources/rmd/hooks.R:55]: If it never makes sense to have `echo = FALSE` for embed then we might just want to set it unqualified? My concern is that there are other formats which set echo = FALSE by default (all the presentation formats, and certainly any dashboard formats we create in the future) so hard-coding to "revealjs" is probably not the thing to do.

Comment (cderv) [reply src/resources/rmd/hooks.R:55]: > that there are other formats which set echo = FALSE by default

I thought we would add them in the list of exception, but I thought we add only revealjs currently. 

> If it never makes sense to have echo = FALSE for embed then we might just want to set it unqualified? 

What do you mean by unqualified ? Not sure to grasp what that entails...

For more context, 

Those formats are all derived from the `cat` engine and are engine with no output but just code part (related to `knitr::engine_output()`). So `echo: FALSE` means nothing will be shown at all, and you probably don't want that, even if you want to hide all the other source code for chunks.

We did not make `echo = TRUE` by default for those engines in this **knitr** because `echo` can be used to filter what to show depending on format (`echo = knitr::is_latex_output()` for example). With Quarto, using expression for `echo` is not what we recommend, so it seems not a problem to do that.

Comment (jjallaire) [reply src/resources/rmd/hooks.R:55]: I was thinking that for those engines running in quarto we just force `echo = TRUE`. The problem with maintaining a list is that it doesn't cover custom formats (i.e. we can't actually know the list).

File: src/core/handlers/base.ts (hunk 1 above)
Comment (cderv) [reply src/core/handlers/base.ts:291]: @cscheid if you can confirm me this is good before we merge. Thank you

Comment (cscheid) [reply src/core/handlers/base.ts:291]: Yes, this looks exactly right, thanks! (just for contrast, I'd have written it as `Object.entries(handlers).filter(([k, v]) => v.type === "cell")` but your code looks 100% correct.)

**Review by cscheid — APPROVED** [review]
lgtm!
