### PR TITLE
Fix typst 0.9.0 output with pandoc 3.1.9 for citations

### LINKED ISSUE #7586: Typst citations does not work since Pandoc 3.1.9
Using **knitr** in the example because it is easy to create a bibliography 
````markdown
---
title: "Test"
format: typst
bibliography: packages.bib
---


```{r}
#| include: false
knitr::write_bib("knitr", "packages.bib")
```

See @R-knitr

````

When rendering 
````
[typst]: Compiling index.typ to index.pdf...error: expected label, found string
    ┌─ \\?\C:\Users\chris\Documents\DEV_OTHER\DEMOS\test-quarto\index.typ:239:10
    │
239 │ See #cite("R-knitr")
    │           ^^^^^^^^^
````

This is a known issue with Pandoc 3.1.9 which is not yet compatible with Typst 0.9.0

* https://github.com/jgm/pandoc/issues/9188

It has been solved for next Pandoc version. 

When we do our dependency refresh (https://github.com/quarto-dev/quarto-cli/pull/7419), we should maybe not update typst to the latest version before Pandoc does a new update after typst release... There will probably always be conflict if they keep doing breaking change in typst 

Should we try to path or just wait for Pandoc new release ? 

By the way, it was not catch in test, because it is not done correctly I believe. I'll PR a change that should show the issue, and we could merge new test when solved

### PR DESCRIPTION
**Pull request by cderv**
This fix test to not just test typ output, because we can't detect issue like #7586

It also solves #7586 by applying the same fix a Typst writer in Pandoc (https://github.com/jgm/pandoc/commit/0283cdc200b7ee44d3abdcc7061c47473ed9fd92)

### CODE REVIEW

File: src/resources/filters/quarto-post/typst.lua [hunk 1]
```diff
@@ -88,6 +88,17 @@ function render_typst_fixups()
         img,
         pandoc.RawInline("typst", "]"),
       })
+    end,
+    Cite = function(cite)
+      -- Patch for https://github.com/quarto-dev/quarto-cli/issues/7586
+      -- TODO: Remove when Pandoc > 3.1.9 is used https://github.com/jgm/pandoc/issues/9188
```
Comment (jjallaire) [inline src/resources/filters/quarto-post/typst.lua:94]: We could even do a Pandoc version test here (so that if we forget to remove the patch we still get correct behavior in the future)

Comment (cderv) [reply src/resources/filters/quarto-post/typst.lua]: Oh good idea ! Done in [fb10edc](https://github.com/quarto-dev/quarto-cli/pull/7587/commits/fb10edc16c596c4dae2ab6a6c5aff90edab88774)
