### PR TITLE
Docusaurus: reactPreamble not rendering

### LINKED ISSUE #8289: [Docusaurus] Tabsets lacks importing modules
### Bug description

It looks like the tabset transform for Docusaurus is broken.
It requires `import Tabs from '@theme/Tabs'; import TabItem from '@theme/TabItem';`

### Steps to reproduce

Copied from #7294

````qmd
---
title: foo
format: docusaurus-md
---

:::{.panel-tabset}

## Not work

```{.python filename="Python"}
print("bar")
```

## Work

```{.python}
print("bar")
```

:::
````

### Expected behavior

````mdx
---
title: foo
format: docusaurus-md
---

import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';

<Tabs>
<TabItem value="Not work">

```python title="Python"
print("bar")
```

</TabItem>
<TabItem value="Work">

``` python
print("bar")
```

</TabItem>
</Tabs>
````

### Actual behavior

````mdx
---
title: foo
format: docusaurus-md
---



<Tabs>
<TabItem value="Not work">

```python title="Python"
print("bar")
```

</TabItem>
<TabItem value="Work">

```python
print("bar")
```

</TabItem>
</Tabs>
````

### Your environment

- Ubuntu 22.04

### Quarto check output

```sh
$ quarto check
Quarto 1.4.538
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.538
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/local/python/current/bin/python3
      Jupyter: 5.7.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /usr/local/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/local/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

### PR DESCRIPTION
**Pull request by cscheid**
Closes #8289. This PR:

- Fixes filter so that `reactPreamble` is rendered to output
- removes `_quarto` from preserved yaml block so that smoke tests are properly run

### CODE REVIEW

File: src/command/render/output.ts [hunk 1]
```diff
@@ -158,10 +160,20 @@ export function outputRecipe(
...
           );
+          // remove _quarto metadata
+          //
+          // this is required to avoid tests breaking due to the
+          // _quarto regexp tests finding themselves in the output
+          const yaml = parseYaml(
+            inputMd.yaml.replace(/^---+\n/m, "").replace(/\n---+\n*$/m, "\n"),
+          ) as Record<string, unknown>;
+          delete yaml._quarto;
+          const yamlString = `---\n${stringifyYaml(yaml)}---\n`;
```
Comment (cderv) [inline src/command/render/output.ts:171]: This just reminded me of another place where we are supposed to do this I believe. 
https://github.com/quarto-dev/quarto-cli/blob/6821f7197aff2b18132e3d1de8720ddaf7599ec9/src/command/render/pandoc.ts#L1087-L1091

Would it mean the above does not work anymore? Or was not needed? 

only asking to clean our code base if we can. 

And I am surprised we got hit by this `ensureFileRegexMatches()` problem only now... 🤯  Good find!

**Comment by cscheid** [comment]
Note that some other tests need fixing here because the `_quarto` key lingering in keep-yaml was causing some tests to be ineffective.

File: src/command/render/output.ts (hunk 1 above)
Comment (cscheid) [reply src/command/render/output.ts:171]: No, those are _separate_ code paths. We need that to be deleted because sometimes the metadata is emitted by Pandoc. But sometimes it's not: see what happens with a plain `markdown` output. It's really annoying, and we should fix in the future.

Comment (cscheid) [reply src/command/render/output.ts:171]: Specifically, the problem is in `hugo-md` and `docusaurus-md`, where the metadata block preservation happens through that code in `output.ts`. It's also annoying (and almost certainly a separate bug) that the frontmatter block that is preserved, in that situation, is only the very first one (like RMarkdown).

But we're not going to pull on that thread right now.
