### PR TITLE
Patch Footnotes when in margin to support multiple paragraph

### LINKED ISSUE #7534: Can't do multiple paragraph footnotes in the margin of a PDF
### Bug description

The PDF version won't compile if the footnotes are put in the margin, and any of the footnotes have more than one paragraph.

This isn't a problem with either margin notes, or multiple paragraph notes. The example below compiles fine if the format is changed to html, the reference-location is changed to document, or the second paragraph is deleted from the footnote.

### Steps to reproduce

````qmd
---
title: "Example"
format: 
    pdf:
        reference-location: margin
---

Some text.[^note] Some more text.

[^note]: The first paragraph.   
    
    The second paragraph.
````

### Expected behavior

A PDF should be built with a two paragraph footnote.

### Actual behavior

It doesn't compile with the following message.

ERROR: 
compilation failed- error
Paragraph ended before \IfNoValueOrEmptyTF  was complete.
<to be read again> 
                   \par 
l.152   The second paragraph.}
                               Some more text. 

### Your environment

- IDE: RStudio Version 2023.09.1+494 (2023.09.1+494)
- Mac running OS 13.6.1 (22G313)

### Quarto check output

Quarto 1.4.470
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.470
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.11
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/weath/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: 5.5.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/miworkspace-library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK

### PR DESCRIPTION
**Pull request by cderv**
As it seems sidenotes CTAN package has an issue and does not handle it correctly, unless using a specific syntax

Fix #7534 

@cscheid this is what you were thinking ?

### CODE REVIEW

**Comment by cscheid** [comment]
Yes, that looks exactly right!

File: src/resources/filters/quarto-post/latex.lua [hunk 1]
```diff
@@ -376,6 +376,13 @@ function render_latex()
       end
       
       return pandoc.Div(calloutContents)
-    end    
+    end,
+    Note = function(n)
+      if marginReferences() then
```
Comment (cscheid) [inline src/resources/filters/quarto-post/latex.lua:381]: I think there's a couple of different ways that notes can end up in the margin. marginReferences() is one of them, but I think there's a way to annotate a div, in which case we need to do something slightly different, by catching the wrapping div first.

Comment (cderv) [reply src/resources/filters/quarto-post/latex.lua:381]: Thanks - I'll look into that then...

Comment (cderv) [reply src/resources/filters/quarto-post/latex.lua:381]: So after looking at others way to do margin content, I do think only `sidenotes` is used for `footnotes` in margin. 

So probably the current solution is enough to cover the issue; 


overview of other ways below

## [Margin Content](https://quarto.org/docs/authoring/article-layout.html#margin-content)

Using `.column-margin` div 
````markdown
::: {.column-margin}

This is a text of several paragraphs in the margin.

Does it works ? 
:::

````

does not have issues because in LaTeX, `\marginnote` command is used, not `\sidenote`

````latex
\marginnote{\begin{footnotesize}

This is a text of several paragraphs in the margin.

Does it works ?

\end{footnotesize}}
````

## [Margin Figures](https://quarto.org/docs/authoring/article-layout.html#margin-figures)

For figures in margin, `\begin{marginfigure}` is used. 

## [Margin Tables](https://quarto.org/docs/authoring/article-layout.html#margin-tables)

`\begin{margintable}` is used, which works ok. 


## [Caption in Margin](https://quarto.org/docs/authoring/article-layout.html#margin-captions)

`\sidecaption` is used.
