### PR TITLE
Asciidoc: don't call pandoc.write()

### LINKED ISSUE #7632: Citations in callouts not processed for AsciiDoc
### Bug description

Citations inside a callout block are not processed when the target is `asciidoc`. The original qmd code (i.e., `[@knuth1984]`) is passed as-is and no entry in the References Div is added.

There's no problem when the div class is not `.callout-*` or when the citation is placed in a footnote.

This problem does not happen for targets `md` and `html`. I have not tried other targets.

### Steps to reproduce

1. Download *references.bib* from https://raw.githubusercontent.com/quarto-dev/quarto-web/dea2b8283307f06a5706693163364bbaf4ef2895/references.bib.
1. Save the code below as *cite-in-callout.qmd*
1. Run `quarto render cite-in-callout.qmd --quiet --to asciidoc --output -`

````qmd
---
title: AsciiDoc Citation Test
bibliography: references.bib
---

## Introduction

Foo [@knuth1984].

::: {.callout-important}
Bar [@wickham2015].
:::

## References {.unnumbered}

::: {#refs}
:::
````

### Expected behavior

```
= AsciiDoc Citation Test

== Introduction

Foo (Knuth 1984).

[IMPORTANT]
====
Bar (Wickham 2015).
====

== References

[[refs]]
[[ref-knuth1984]]
Knuth, Donald E. 1984. “Literate Programming.” _The Computer Journal_ 27 (2): 97–111.

[[ref-wickham2015]]
Wickham, Hadley. 2015. _R Packages_. 1st ed. O’Reilly Media, Inc.
```

### Actual behavior

```
= AsciiDoc Citation Test

== Introduction

Foo (Knuth 1984).

[IMPORTANT]
====
Bar [@wickham2015].
====

== References

[[refs]]
[[ref-knuth1984]]
Knuth, Donald E. 1984. “Literate Programming.” _The Computer Journal_ 27 (2): 97–111.
```

### Your environment

- IDE: vim
- OS: macOS 12.5

### Quarto check output

````
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: /Users/jeroen/.pyenv/versions/3.11.1/bin/python3
      Jupyter: 5.3.1
      Kernels: python3

(-) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /opt/homebrew/Cellar/r/4.3.1/lib/R
      LibPaths:
        - /opt/homebrew/lib/R/4.3/site-library
        - /opt/homebrew/Cellar/r/4.3.1/lib/R/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK
````

### PR DESCRIPTION
**Pull request by cscheid**
Closes #7632 

Somehow, `pandoc.write(doc, "asciidoc")` is producing different outputs from the "regular" asciidoc writer that we get by sending the AST to Pandoc. This fixes the problem.

### CODE REVIEW

File: src/resources/filters/quarto-post/render-asciidoc.lua [hunk 1]
```diff
@@ -60,16 +60,26 @@ function render_asciidoc()
       -- render the callout contents
       local admonitionContents = pandoc.write(pandoc.Pandoc(el.content), "asciidoc")
```
Comment (cderv) [inline src/resources/filters/quarto-post/render-asciidoc.lua:61]: I believe you can remove this now right ?

Comment (cscheid) [reply src/resources/filters/quarto-post/render-asciidoc.lua:61]: Oh yeah, thanks. I wish the Lua mode were more aggressive in showing unused variables.

Comment (cscheid) [reply src/resources/filters/quarto-post/render-asciidoc.lua:61]: Fixed on `main`.
