### PR TITLE
Improved fix for 5089

### LINKED ISSUE #5089: Nonstandard image URL won't render (PDF)
### Bug description

I'm trying to render this page as PDF. 
```qmd
---
title: Non-standard URL
---


![](https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F9b7345d9-5f62-46dc-8062-d704c2c014a5_289x174.jpeg)
```

Breaks with this error:

```
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages

compilation failed- error
Unable to load picture or PDF file 'badurl_files/mediabag/https://bucket.jpeg'.
<to be read again> 
                   }
l.159 ...adurl_files/mediabag/https://bucket.jpeg}
```

Quarto version 1.3.306
OSX 13.3

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

### PR DESCRIPTION
**Pull request by dragonstyle**
Fixes #5089

Improvements include:

1) If the URL has been encoded repeatedly, we will continue decoding the URL until it is completely decoded.

2) If the file extension guessed from the URL doesn’t match the mime type, we will respect the mime type and use that to form the file name.

This URL:
https://substackcdn.com/image/fetch/w_1456,c_limit,f_webp,q_auto:good,fl_progressive:steep/https%253A%252F%252Fsubstack-post-media.s3.amazonaws.com%252Fpublic%252Fimages%252Fced5d5ad-a0d6-44aa-b6f5-73c0a937d016_3553x5273.jpeg

is double URL encoded and returns a webp file (which can’t be rendered in PDFs, FYI).

### CODE REVIEW

File: src/resources/filters/quarto-post/pdf-images.lua [hunk 1]
```diff
@@ -126,6 +143,7 @@ function pdfImages()
                     counter = counter + 1
                   end
                   resolvedUrls[image.src] = filename
+                  quarto.log.output({filename, imgMt})
```
Comment (cscheid) [inline src/resources/filters/quarto-post/pdf-images.lua:146]: (plink) _puts quarter into log jar_

**Review by cscheid — APPROVED** [review]
aside from writing an actual table rather than grabbing the regex capture, this LGTM
