### PR TITLE
bug/giscus-dark-toggle

### LINKED ISSUE #4820: When using a dark theme, giscus should use a dark theme as well.
### Bug description

Right now `giscus` uses a light theme by default even when a dark theme is toggled. 

image

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

### PR DESCRIPTION
**Pull request by ghost**
#closes https://github.com/quarto-dev/quarto-cli/issues/4820

### CODE REVIEW

File: src/core/giscus.ts [hunk 1]
```diff
@@ -39,3 +39,41 @@ export async function getGithubDiscussionsMetadata(repo: string) {
...
+
+export const buildGiscusThemeKeys = (
+  darkModeDefault: boolean,
+  theme: GiscusTheme
+): GiscusThemeToggleRecord => {
+  if (typeof theme === "string") {
+    if (theme.length > 0) {
+      return { baseTheme: theme, altTheme: theme };
+    } else {
+      theme = { light: "light", dark: "dark" };
```
Comment (allenmanning) [inline src/core/giscus.ts:61]: Extract as constants.

File: src/format/html/format-html.ts [hunk 2]
```diff
@@ -467,8 +470,17 @@ export async function htmlFormatExtras(
   // giscus
   if (options.giscus) {
     const giscus = options.giscus as Record<string, unknown>;
+
     giscus.category = giscus.category || "General";
-    giscus.theme = giscus.theme || "light";
+    giscus.theme = giscus.theme || "";
+
+    const themeToggleRecord:GiscusThemeToggleRecord =
+        buildGiscusThemeKeys(!!options.darkModeDefault, giscus.theme as GiscusTheme)
```
Comment (allenmanning) [inline src/format/html/format-html.ts:478]: Is there a better option here than `!!` I'm hoping for something cleaner.

File: src/resources/formats/html/templates/quarto-html.ejs [hunk 3]
```diff
@@ -53,6 +53,52 @@ window.document.addEventListener("DOMContentLoaded", function (event) {
     }
   }
 
+
+  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
+    console.log('toggleGiscusIfUsed');
```
Comment (allenmanning) [inline src/resources/formats/html/templates/quarto-html.ejs:58]: Remove `console.log`

**Review by rich-iannone — APPROVED** [review]
This looks good and the included tests cover the changes made. Minor nit (take it or leave it) is to include a space after using `if` (in two instances).

File: src/core/giscus.ts [hunk 4]
```diff
@@ -39,3 +39,46 @@ export async function getGithubDiscussionsMetadata(repo: string) {
...
+    } else {
+      theme = { light: GiscusThemeDefault.light, dark: GiscusThemeDefault.dark };
+    }
+  }
+
+  const themeRecord: { light: string; dark: string } = theme as {
+    light: string;
+    dark: string;
+  };
+  let result = {
```
Comment (dragonstyle) [inline src/core/giscus.ts:74]: This is generating a lint warning since `result` isn't reassigned.

**Review by dragonstyle — APPROVED** [review]

File: src/core/giscus.ts (hunk 4 above)
Comment (allenmanning) [reply src/core/giscus.ts:74]: How are you running lint to see this?

When I `deno lint` on the quarto cli directory I see `1999 problems`.  I also checked "Check" in our builders and I wasn't able to find a lint log.

Comment (dragonstyle) [reply src/core/giscus.ts:74]: I have Deno linting configured in VS.Code (via their LSP) so I see listing for files that I open. We don't currently have a great project wide linting configuration :(

File: src/resources/editor/tools/yaml/yaml-intelligence-resources.json [hunk 5]
```diff
@@ -4096,6 +4113,26 @@
           }
         }
       }
+    },
```
Comment (allenmanning) [inline src/resources/editor/tools/yaml/yaml-intelligence-resources.json:4116]: @dragonstyle I suspect this is because you (or someone) updated the YML without running `build-js` so it is coming along for a ride on my PR.  Is this a problem or should I just merge it in?
