### PR TITLE
move docusaurus custom nodes to new renderer api

### LINKED ISSUE #7294: [Docusaurus] "Warning: couldn't recognize format, using default tabset rendering" and tabset rendered incorrectly
### Bug description

It seems that the `docusaurus-md` format's tabset no longer works

### Steps to reproduce

I found this issue on <https://github.com/eitsupi/querying-with-prql/tree/4dcdfd6b58d7860ae6d29f9299ef1175f309061e>

Render this qmd file. (from #5190)

````qmd
---
title: foo
format: docusaurus-md
---

:::{.panel-tabset}

## Not work

```{.python filename="Python"}
print("bar")
```

## Work

```{.python}
print("bar")
```

:::
````

### Expected behavior

````md
---
title: foo
format: docusaurus-md
---

import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';

<Tabs>
<TabItem value="Not work">

```python title="Python"
print("bar")
```

</TabItem>
<TabItem value="Work">

``` python
print("bar")
```

</TabItem>
</Tabs>

````

### Actual behavior

````md
---
title: foo
format: docusaurus-md
---

## Not work

**Python**

```python title="Python"
print("bar")
```

## Work

```python
print("bar")
```
````

And warning on the console.

```sh
$ quarto render test.qmd 
pandoc 
  to: >-
    markdown_strict+raw_html+all_symbols_escapable+backtick_code_blocks+fenced_code_blocks+space_in_atx_header+intraword_underscores+lists_without_preceding_blankline+shortcut_reference_links+autolink_bare_uris+emoji+footnotes+gfm_auto_identifiers+pipe_tables+strikeout+task_lists+tex_math_dollars+pipe_tables+tex_math_dollars+header_attributes+raw_html+all_symbols_escapable+backtick_code_blocks+fenced_code_blocks+space_in_atx_header+intraword_underscores+lists_without_preceding_blankline+shortcut_reference_links
  output-file: test.md
  standalone: true
  default-image-extension: png
  wrap: none
  html-math-method: webtex
  
metadata
  title: foo
  
Warning: couldn't recognize format, using default tabset rendering
Output created: test.md
```

### Your environment

- OS: Ubuntu 22.04 amd64

### Quarto check output

```sh
$ quarto check
Quarto 1.4.424
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.424
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/local/python/current/bin/python3
      Jupyter: 5.4.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/local/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/local/lib/R/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

### PR DESCRIPTION
**Pull request by cscheid**
Closes #7294.

### CODE REVIEW

File: src/resources/extensions/quarto/docusaurus/docusaurus_writer.lua [hunk 1]
```diff
@@ -51,38 +51,42 @@ local function tabset(node, filter)
...
+end, function(node)
+  local el = node.code_block
+  return code_block(el, node.filename)
+end)
+
+function Writer(doc, opts)
+  doc = quarto._quarto.ast.walk(doc, {
+    CodeBlock = code_block,
+  })
+  assert(doc ~= nil)
```
Comment (cderv) [inline src/resources/extensions/quarto/docusaurus/docusaurus_writer.lua:89]: @cscheid Curious to learn more: Is `assert()` in our Lua code a way to had some checks to error early on some feature ? 
Will that create a good error message ? 

I am not using that currently, but always keen to learn new practice ! (which reading others code is always good for !)

 thanks

Comment (cscheid) [reply src/resources/extensions/quarto/docusaurus/docusaurus_writer.lua:89]: It's a lua-specific thing I only recentlly learned about. In this case that should really never happen, and if it ever did, the error message won't be particularly helpful. It's there because the lua analyzer in the vs code extension knows about it, so it assumes `doc ~= nil` in the lines following the assertion.

I used to write 

```
if doc ~= nil then
  -- luacov: disable
  internal_error() 
  return
  -- luacov: enable
end
```

(the `luacov` statements are telling the lua code coverage tool that those lines shouldn't be counted)

As you can see, that's a lot more lines for the same effect.

Comment (cderv) [reply src/resources/extensions/quarto/docusaurus/docusaurus_writer.lua:89]: > It's there because the lua analyzer in the vs code extension knows about it, so it assumes doc ~= nil in the lines following the assertion.

TIL ! Thanks. I'll try to use more of `assert()` now.
