### PR TITLE
brand - warn on invalid color name usage

### LINKED ISSUE #11665: `background` doesn't work as a color in `revealjs` unless it's explicitly set
repro:

```qmd
---
title: Hello, `_brand.yml`!
brand:
  typography: 
    monospace:
      family: Inconsolata
      size: 1em
      color: foreground
      background-color: background
    base:
      family: Open Sans
    headings:
      family: Montserrat
    fonts:
      - family: Inconsolata
        source: google
      - family: Open Sans
        source: google
      - family: Montserrat
        source: google
---

## Links

Download the Positron Beta here: <https://positron.posit.co/download.html>

Docs for `_brand.yml`: <https://posit-dev.github.io/brand-yml/>, <https://quarto.org/docs/authoring/brand.html>

## Placeholder text

This is an example document with a [number](https://quarto.org) of `features` to help you come with a nicely branded document.

Duis ornare ex ac iaculis pretium. Maecenas sagittis odio id erat pharetra, sit amet consectetur quam sollicitudin. Vivamus pharetra quam purus, nec sagittis risus pretium at. Nullam feugiat, turpis ac accumsan interdum, sem tellus blandit neque, id vulputate diam quam semper nisl. Donec sit amet enim at neque porttitor aliquet. Phasellus facilisis nulla eget placerat eleifend. Vestibulum non egestas eros, eget lobortis ipsum. Nulla rutrum massa eget enim aliquam, id porttitor erat luctus. Nunc sagittis quis eros eu sagittis. Pellentesque dictum, erat at pellentesque sollicitudin, justo augue pulvinar metus, quis rutrum est mi nec felis. Vestibulum efficitur mi lorem, at elementum purus tincidunt a. Aliquam finibus enim magna, vitae pellentesque erat faucibus at. Nulla mauris tellus, imperdiet id lobortis et, dignissim condimentum ipsum. Morbi nulla orci, varius at aliquet sed, facilisis id tortor. Donec ut urna nisi.
```

`quarto render --to html` works, `quarto render --to revealjs` doesn.t

### PR DESCRIPTION
**Pull request by cscheid**
Closes #11665.

(@gordonwoodhull, I'm asking for a review from you because I think you've written CSS color detectors in your typst work. I'd love to know if we're missing anything with `isCssColorName` specifically. Thanks!)

### CODE REVIEW

**Review by cderv — APPROVED** [review]
I added a simple test for now just about the presence of the warning so we don't lose it in the future.

Testing for the revealjs error seems odd as it happens only in a specific case with `background-color`

I'll also improve `printMessage` verify function in another PR so we can test multiple regexes. 
I'll modify this test there so that we test also for no warn on some known color.

File: src/core/css/color-names.ts [hunk 1]
```diff
@@ -0,0 +1,163 @@
...
+ *
+ * Copyright (C) 2025 Posit Software, PBC
+ */
+
+// https://www.w3.org/TR/css-color-3/#svg-color
+export const isCssColorName = (name: string): boolean => {
+  if (name.startsWith("#")) return true;
+  if (name.startsWith("rgb")) return true;
+  if (name.startsWith("hsl")) return true;
+  if (name.startsWith("hwb")) return true;
```
Comment (gordonwoodhull) [inline src/core/css/color-names.ts:12]: There are a lot more color spaces than this, but this should be fine.

File: src/core/css/color-names.ts [hunk 2]
```diff
@@ -0,0 +1,163 @@
...
+    "teal",
+    "thistle",
+    "tomato",
+    "turquoise",
+    "violet",
+    "wheat",
+    "white",
+    "whitesmoke",
+    "yellow",
+    "yellowgreen",
```
Comment (gordonwoodhull) [inline src/core/css/color-names.ts:161]: I think I used the same source for named colors in `typst_css.lua`, found a JSON test file in the spec.

`transparent` is also important, [once a keyword, now a color](https://developer.mozilla.org/en-US/docs/Web/CSS/named-color#transparent)

I see both of us missed `rebeccapurple`, the other color defined after the original spec.

**Review by gordonwoodhull — APPROVED** [review]
