### PR TITLE
Escape revealjs lib url in metadata using new pandoc-native inline

### LINKED ISSUE #9117: if qmd filename contains "--" inside, quarto isnt working correctly processing CSS reveal
### Bug description

Hello, 

if i put "--" inside the filename , quarto is throwing following errors:

```bash

`PS D:\z_HS\proj\Techn_DE\inhalte_technischedatenerfassung\00_Inhalte> quarto preview d:/z_HS/proj/Techn_DE/inhalte_technischedatenerfassung/00_Inhalte/test01--04.qmd --no-browser --no-watch-inputs
pandoc 
  to: revealjs
  from: markdown+emoji
  output-file: test01--04.html
  standalone: true
  self-contained: false
  wrap: none
  default-image-extension: png
  html-math-method:
    method: mathjax
    url: >-
      https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML-full
  slide-level: 3
  toc: true
  toc-depth: 1
  number-sections: true
  css:
    - style.css
  
metadata
  link-citations: true
  width: 1050
  height: 700
  margin: 0.1
  center: false
  navigationMode: linear
  controlsLayout: edges
  controlsTutorial: false
  hash: true
  history: true
  hashOneBasedIndex: false
  fragmentInURL: false
  transition: none
  backgroundTransition: none
  pdfSeparateFragments: false
  lang: en
  auto-stretch: true
  theme:
    - default
    - _extensions/grantmcdermott/clean/clean.scss
  menu:
    side: left
  slideNumber: c/t
  date-format: long
  title: 'test '
  author:
    name: test
    orcid: 0000-0021-7213-4711
    email: mr@test.com
    affiliations: company x
  copyright:
    holder: Prof. Mario Roßdeutscher
    year: 2023
  license: CC BY
  date: last-modified
  bibliography:
    - refs.bib
  toc-title: TOC
  footer: footer test
  logo: images/HochschuleEsslingen_Logo_Goeppingen_SW_DE.png
  scrollable: true

Output created: test01--04.html

Watching files for changes
Browse at http://localhost:3942/test01--04.html
ERROR: 500 (Internal Error): Unexpected end of JSON input
  /test01–04_files/libs/revealjs/dist/reset.css (404: Not Found)
  /test01–04_files/libs/revealjs/dist/reveal.css (404: Not Found)
  /test01–04_files/libs/revealjs/dist/theme/quarto.css (404: Not Found)
  /test01–04_files/libs/revealjs/dist/reveal.js (404: Not Found)
  /test01–04_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js (404: Not Found)
  /test01–04_files/libs/revealjs/plugin/reveal-menu/menu.js (404: Not Found)
  /test01–04_files/libs/revealjs/plugin/pdf-export/pdfexport.js (404: Not Found)
  /test01–04_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js (404: Not Found)
  /test01–04_files/libs/revealjs/plugin/quarto-support/support.js (404: Not Found)
  /test01–04_files/libs/revealjs/plugin/notes/notes.js (404: Not Found)
  /test01–04_files/libs/revealjs/plugin/search/search.js (404: Not Found)
  /test01–04_files/libs/revealjs/plugin/math/math.js (404: Not Found)
  /test01–04_files/libs/revealjs/plugin/zoom/zoom.js (404: Not Found)
  /test01–04_files/libs/revealjs/dist/reveal.js (404: Not Found)
  /test01–04_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js (404: Not Found)
  /test01–04_files/libs/revealjs/plugin/pdf-export/pdfexport.js (404: Not Found)
  /test01–04_files/libs/revealjs/plugin/reveal-menu/menu.js (404: Not Found)
  /test01–04_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js (404: Not Found)
  /test01–04_files/libs/revealjs/plugin/quarto-support/support.js (404: Not Found)
  /test01–04_files/libs/revealjs/plugin/notes/notes.js (404: Not Found)
  /test01–04_files/libs/revealjs/plugin/search/search.js (404: Not Found)
  /test01–04_files/libs/revealjs/plugin/zoom/zoom.js (404: Not Found)
  /test01–04_files/libs/revealjs/plugin/math/math.js (404: Not Found)
`
```

### Steps to reproduce

Here is the qmd and html file attached 

[00_Inhalte.zip](https://github.com/quarto-dev/quarto-cli/files/14626952/00_Inhalte.zip)

and here is the content of the file 

````qmd
---
title: "test "
from: markdown+emoji
format:
  revealjs:
    self-contained: false
    footer: "footer test"
    slide-number: c/t
    slide-level: 3
    css: style.css
    scrollable: true
  html:
    mermaid:
      theme: dark
    embed-resources: false
    link-external-icon: true
    link-external-newwindow: true
    tbl-cap-location: bottom
author:
    name: "test"
    orcid: 0000-0021-7213-4711
    email: mr@test.com
    affiliations: company x
date: last-modified
toc: true
toc-title: TOC
toc-depth: 1
number-sections: true
execute:
    echo: true
---

a little test
````

### Expected behavior

as it works normally, when we just rename the file from test01--04.qmd to test01-04.qmd

### Actual behavior

see the above error, the html file is built, but without CSS styling

### Your environment

Windows 10
IDE: Visual Studio Code
Quarto: 1.4.549

### Quarto check output

```bash
Quarto 1.4.549
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.549
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.5 (Conda)
      Path: D:/Programme/anaconda3/python.exe
      Jupyter: 5.3.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### PR DESCRIPTION
**Pull request by cderv**
This syntax was introduced in #9159 and help solve cases like this where we need to prevent pandoc from parsing as Markdown the metadata fields passed in the YAML file used with `metadata-file:`

For context about `--metadata-file` see https://pandoc.org/MANUAL.html#option--metadata-file
> Read metadata from the supplied YAML (or JSON) file. This option can be used with every input format, but string scalars in the metadata file will always be parsed as Markdown. 

fixes #9117

### CODE REVIEW

File: src/format/reveal/format-reveal-theme.ts [hunk 1]
```diff
@@ -85,7 +85,7 @@ export async function revealTheme(
   const revealUrl = pathWithForwardSlashes(revealDir);
   // escape to avoid pandoc markdown parsing from YAML default file
   // https://github.com/quarto-dev/quarto-cli/issues/9117
-  metadata[kRevealJsUrl] = pandocNativeStr(revealUrl);
+  metadata[kRevealJsUrl] = pandocNativeStr(revealUrl).mappedString().value;
```
Comment (cderv) [inline src/format/reveal/format-reveal-theme.ts:88]: @cscheid is this the correct way to use the `pandocNativeStr` generator ? 

I looked at the test you made and fix my issue following it. 

I see the codegen function have `emit()` `mappedString()` and others. Probably a quick run through how all this works would help me. I see it is used for mermaid only for now.

Comment (cscheid) [reply src/format/reveal/format-reveal-theme.ts:88]: In this context, yes, that's exactly how I would use it. That codegen.ts module has features to maintain source information (useful for error messages) but those are not going to be usable in here, so yes, I think this looks good.

Comment (cderv) [reply src/format/reveal/format-reveal-theme.ts:88]: > That codegen.ts module has features to maintain source information (useful for error messages)

Oh so that is what I am missing. I have seen Mapped string thing in other place, but not yet sure to know how it works; Thanks ! 

I'll add a note in changelog and merge when tests pases
