### PR TITLE
make utils.dump more robust to pandoc internal objects. Closes #2254

### LINKED ISSUE #2254: `quarto.utils.dump` doesn't work with PANDOC_STATE

### PR DESCRIPTION
**Pull request by cscheid**
This Lua filter produces a good output now:

```
Pandoc = function(doc)
  quarto.utils.dump({
    PANDOC_READER_OPTIONS = PANDOC_READER_OPTIONS,
    PANDOC_WRITER_OPTIONS = PANDOC_WRITER_OPTIONS,
    PANDOC_VERSION = PANDOC_VERSION,
    FORMAT = FORMAT,
    PANDOC_VERSION = PANDOC_VERSION,
    PANDOC_API_VERSION = PANDOC_API_VERSION,
    PANDOC_SCRIPT_FILE = PANDOC_SCRIPT_FILE,
    PANDOC_STATE = PANDOC_STATE,
    pandoc = pandoc,
    lpeg = lpeg,
    re = re  
  })
end 
```

### CODE REVIEW

**Comment by tarleb** [comment]
Apologies for waltzing into this PR, but I believe it might be a good opportunity for me to learn more about the ways in which pandoc's Lua could be improved.

We try to make properties accessible via `for key, value in pairs(...) do ...`; could this be used here? If not, what kind of change would make it easier to handle this issue?

File: src/resources/filters/common/debug.lua [hunk 1]
```diff
@@ -44,4 +36,88 @@ function tdump (tbl, indent, refs)
...
+-- objects ahead of debug printing
+function asLua(o)
+  if type(o) ~= 'userdata' then
+    return o
+  end
+  local p = string.format("%p", o)
 
+  -- we check equality against the addresses to work around
+  -- https://github.com/jgm/pandoc/issues/8267
+  if p == string.format("%p", PANDOC_READER_OPTIONS) then
```
Comment (tarleb) [inline src/resources/filters/common/debug.lua:49]: This is a beautiful hack. The problem in 8267 is the `__eq` metamethod, which we could skip with `rawequal(o, PANDOC_READER_OPTIONS)`.

Comment (cscheid) [reply src/resources/filters/common/debug.lua:49]: TIL about `rawequal`, thank you!

**Comment by cscheid** [comment]
Don't apologize: I appreciate the opportunity to learn! I'm sure you'll find that my Lua knowledge is, um, lacking :)

It's also possible that `for key, value in pairs()` works, but I wasn't confident that it would not fail badly in some other cases, and since I can't reach for something like `try except`, I went for the conservative approach.

**Comment by tarleb** [comment]
Thanks :) In that case, allow me to spill a few more details about Haskell "userdata objects" on you; it is just fyi and safe to ignore.

Haskell-generated userdata objects have three main components: a type name, properties, and methods:

The *name* can be retrieved with `pandoc.utils.type` or `function (x) return debug.getmetatable(x).__name end`. The latter is actually a bit faster in case you ever need to do this in a tight loop, but it's also less robust.

*Properties* are "lazy", in that we only marshal the values when the property is accessed for the first time. This is useful with large objects like `Pandoc`, that would otherwise take much longer to marshal. However, this lazy marshaling is slower if all properties will be accessed anyway. If you run into performance issues, then this would be a good place for us to start.

Methods are just wrapped Haskell functions.

We discourage modifications to the underlying object metatables, which is why `getmetatable` returns `true` instead of the actual metatable. It's still possible to inspect and modify the metatable with the help of `debug.getmetatable`, but here be dragons.

The properties and methods are listed when iterating over them with `pairs`. The order is defined at compile time, with properties listed first, followed by methods. We usually try to keep each of these alphabetical, but there may be exceptions.

Some objects also have property aliases: E.g., `div.classes` is really just an alias for `div.attr.classes`, and they point to the same list. Aliases are not included when using `pairs`.

In theory, we also have support for objects that behave like lists, but pandoc doesn't make use of that feature.

Both, error handling and the generic `for` loop, are a bit weird. Code to check if `pairs` yields reasonable results could look like this:

``` lua
local success, iterator, state, control_var, closing = pcall(pairs, my_object)
if success and iterator then
  for key, value in iterator, state, control_var, closing do
  end
end
```

There is also an undocumented feature that I plan to extend in the future: documentation is available through Lua. E.g., to get the documentation for `pandoc.read`, one would write:

``` lua
debug.getregistry()['HsLua docs'][pandoc.read]
```

The resulting table contains info on the name of the functions, its arguments, etc.

**Comment by tarleb** [comment]
I've cleaned, corrected, and extended the above info into a proper blog post. The section on *Internals* might be of interest for the `utils.dump` function: https://tarleb.com/posts/haskell-lua-objects/#internals
