### PR TITLE
register cleanup for sassCache

### LINKED ISSUE #10368: On windows, error while removing quarto-sessions temp dir
I am seeing this 

````
WARN: Error removing file C:\Users\chris\AppData\Local\Temp\quarto-session4dc6ef4c3471c0e7\8e1f6186cca530ee: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus. (os error 32): remove 'C:\Users\chris\AppData\Local\Temp\quarto-session4dc6ef4c3471c0e7\8e1f6186cca530ee'
Output created: index.html

Error occurred with cleanup handlers:Error: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus. (os error 32): remove 'C:\Users\chris\AppData\Local\Temp\quarto-session4dc6ef4c3471c0e7'
````

I decided to look into this, and it happens in 
https://github.com/cderv/quarto-cli/blob/f9d1301be63133210a492a04fa02d22e1a5e5111/src/core/temp.ts#L38-L47

Somehow it is called with `tempContext` being undefined but `tempDir` not empty. And on windows, `Deno.removeSync` throug this error reported by Quarto 
````
Uncaught Error Error: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus. (os error 32): remove 'C:\Users\chris\AppData\Local\Temp\quarto-sessionf7c75ac2832789eb'
    at removeSync (deno_fs/30_fs.js:250:3)
    at eval (repl:1:6)
````

So I thought of some OS locking issue and what I am seeing by looking at what could cause the lockup on windows is 
image

The PID is the same as the current `Deno.pid` in debug mode I have. So somehow, some of the content of the quarto session temp directory we use for sass bundling probably is still lock on the files. 

This means the session directory can't be cleanup. And I got a lot of those it seems !! 

````r
> length(fs::dir_ls(Sys.getenv("TEMP"), regexp = "quarto-session.*/.*/sass/.*", recurse = TRUE))
[1] 393
````

So something is not right here... 

I believe it happens only with pre-release, so should be quite recent change

### PR DESCRIPTION
**Pull request by cderv**
This solves #10368 

First, opening for review. I still need to add some tests in this PR before we merge. 

This is a follow up on 
- https://github.com/quarto-dev/quarto-cli/pull/10218

so that opened Deno.kv connection are correctly closed  before we try to delete the create files. 

Challenge are the following 
- It happens we cleanup in several places 
	- Render services cleanup after render
	- on exit cleanup at the very end 
- At first I tried to add on exit cleanup, but in fact we clean TempContext earlier right after render, while cleaning all render services. 
- Sass Cache cleanup needs to happen before cleaning Temp Context or during Temp Context cleanup itself. 
- Though we have one of the Sass Cache that is not in Quarto Session Dir but on user cacher directory. This Deno.kv also needs to be closed before we exit (so that we do things cleanly). 

This PR is a proposal with the following to resolve thoses challenges

- It adds a mechanism to add cleanup handler to a TempContext. 
- SassCache using a TempContext can register a specific cleaning handler
- Other SassCache not using a TempContext (persistent cache) are cleanup as quarto exit handler, and cache db file is not removed)

We could do differently probably 
- As I believe we always create a temp context, we could attach all SassCache cleanup to TempContext cleanup phase, which will happen after render.
- Maybe we need more generic process where SassCache kv db should be a new render services where cleanup is attached to lifetime `kRenderServicesLifetime` object. Or even in this case a single kv db for all things we need to cache that would be available as a CacheContext like TempContext, and following same logic of being attach to lifetime object. 

Any how, I did the more obvious and easy to me. Testing locally, it solves this  and cleanup is working well !

### CODE REVIEW

File: src/core/sass/cache.ts [hunk 1]
```diff
@@ -155,6 +156,21 @@ class SassCache {
...
     );
   }
+
+  // add a cleanup method to register a cleanup handler
+  cleanup(temp: TempContext | undefined) {
+    const registerCleanup = temp ? temp.onCleanup : onCleanup;
+    registerCleanup(() => {
+      try {
+        this.kv.close();
+        if (!temp) safeRemoveIfExists(this.path);
```
Comment (cscheid) [inline src/core/sass/cache.ts:166]: What is this call to `safeRemoveIfExists` doing? I'm not sure I understand. We shouldn't remove that path.

**Review by cscheid — CHANGES_REQUESTED** [review]
I think that new call to `safeRemoveIfExists` is wrong, see below.

File: src/core/sass/cache.ts (hunk 1 above)
Comment (cderv) [reply src/core/sass/cache.ts:166]: yes this is indeed wrong. Thanks for catching it ! 
I really meant 
```suggestion
        if (temp) safeRemoveIfExists(this.path);
```

We don't need to keep the sass cache dir when we create it as a temporary context. Though all TempContext and the Session temp `quarto-session*` folder will be deleted at some point by cleanup process. This is just a habit of making sure to remove from filesystem anything that code is creating, when not needed anymore. 

I understand you are suggesting to not do that for simplicity sake ?

Comment (cscheid) [reply src/core/sass/cache.ts]: I just wanted to make sure that we're not deleting the system-wide cache that will be used when `useSessionCache` is false:

https://github.com/quarto-dev/quarto-cli/blob/6796ddfd42c87efbc1648b48125c742f12dd90c1/src/core/sass.ts#L307-L311

Comment (cderv) [reply src/core/sass/cache.ts]: All good then. Thanks for catching up my faulty condition !

**Comment by cderv** [comment]
And so our tests suite would have find the error with the correct warning checks. 

I am not adding more checks then, also because I am unsure how to test that the Quarto session temp dir has correctly been removed. After all, it should not be necessary to test it because our cleanup would have throw a warning, that we now detect, and all our smoke-all tests checks for `noErrorsOrWarnings`. 

This should be good now !
