### PR TITLE
Fix no inspectable targets issue with Chrome Browser

### LINKED ISSUE #4653: ERROR: "No inspectable targets"-error when rendering PDF containing Mermaid diagram
### Bug description

Hello,

Í'm using:
- Latest version of R (4.2.2)
- Latest version of Rstudio  (2022.12.0 Build 353)
- Latest Quarto (version 1.2.335)
- Windows 10 Enterprise 22H2

When rendering a PDF from a .QMD-file containing a Mermaid diagram [(https://quarto.org/docs/authoring/diagrams.html)](https://quarto.org/docs/authoring/diagrams.html), my Rstudio gives the error "ERROR: No inspectable targets" and crashes (I'm unable to press stop).
In the past the same .QMD file rendered to PDF without any problem. Rendering to .HTML still works. The same error was recently reported by an Obsidian user: [https://forum.obsidian.md/t/about-quarto-no-inspectable-targets-error/54757](https://forum.obsidian.md/t/about-quarto-no-inspectable-targets-error/54757).

The .QMD-file i'm using can be found in the attached .ZIP (Github doesn't allow uploading QMD's directly, therefore I zipped).

Thanks for the good work!

Best,
Thomas

[testdia.zip](https://github.com/quarto-dev/quarto-cli/files/10902790/testdia.zip)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

### PR DESCRIPTION
**Pull request by cderv**
Fix #4653 

Issue is that somehow Chrome browser open in headless mode with no target available at `json/` endpoint. 

The logic to solve is to create a new tab if no target is already available. This way there will be a new target with websocket url to use. 

Another solution would be to default to `json/version` endpoint  (`devtools.Version(option)` from `devtools.js`)  to get the browser websocket url 

But it feels like the former is good enough and better as we prefer page type for the ws url, so I went with that. 

This PR will add to the `defaultTarget()` handler the creation of a new tab using `json/new` if no targets is to inspect. 
I wasn't sure where to put this here or not, we could also move it upper in the stack in `_fetchDebuggerURL()` directly, instead of only `defaultTarget()`. It would be more generic. 

This PR also fix an issue I found while working on it  - if `client` is created without error, no need to try `maxTries` (5) times 

Hope this is good. Not sure how to add tests for this quite specific fix. 

Tested locally and it works for me.

### CODE REVIEW

File: src/core/cri/cri.ts [hunk 1]
```diff
@@ -114,6 +114,7 @@ export async function criClient(appPath?: string, port?: number) {
       for (let i = 0; i < maxTries; ++i) {
         try {
           client = await cdp({ port });
+          break;
```
Comment (cscheid) [inline src/core/cri/cri.ts:117]: Nice catch 🤦

**Review by cscheid — APPROVED** [review]
with respect to changes on `chrome.js`: you'll note that this is a port of a library written by someone else. Fantastic that you found the issue and fixed it.

But I wonder if we should also check the upstream for updates, and set up a more formal fork rather than just change this one directly. (We can do that during 1.4)

**Comment by cscheid** [comment]
> Not sure how to add tests for this quite specific fix.

This code path should be getting tested during our mermaid rendering tests. Ideally we'd make an isolated test, but I think we're at least covered.

**Comment by cderv** [comment]
> with respect to changes on `chrome.js`: you'll note that this is a port of a library written by someone else. Fantastic that you found the issue and fixed it.
> 
> But I wonder if we should also check the upstream for updates, and set up a more formal fork rather than just change this one directly. (We can do that during 1.4)

I did not realize this one file from a library 🤦 it was in `core` so I thought it was ours but now I see the head of the file and the copyright and author 😅 

Do you know the repo for this ? I can PR there maybe

Otherwise in #4704 we can do a git patch approach as I recently add to `updateGithubSourceCodeDependency` for PdfExport plugin in Reveal https://github.com/quarto-dev/quarto-cli/blob/3e3ddeac2d812d1b17d64a9971963df8e6c84959/package/src/common/update-html-dependencies.ts#L826
