### PR TITLE
5815-bug-confluence-links-to-file-attachments-not-supported

### LINKED ISSUE #5815: Confluence:  Links to file attachments not supported
### Bug description

Links to file attachments not supported

### Steps to reproduce

- Create a simple quarto document that creates a link to a file
```
---
title: "Bug: Links to attachemnts not supported"
---

[quarto-hex.svg](images/quarto-hex.svg)
```

### Expected behavior

The image is uploaded as an attachment to the document and linked.  The link works and opens the attached file.

### Actual behavior

No attachment is uploaded.  It renders just text instead of a link.

### Your environment

Mac

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /Users/amanning/projects/github/quarto/quarto-cli/package/dist/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
      Jupyter: 5.2.0
      Kernels: julia-1.7, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      knitr: 1.42
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

### PR DESCRIPTION
**Pull request by ghost**
fixes #5815

### CODE REVIEW

File: src/publish/confluence/confluence-helper.ts [hunk 1]
```diff
@@ -833,16 +833,18 @@ export const findAttachments = (
   publishFiles: string[] = [],
   filePathParam: string = "",
 ): string[] => {
+  console.log('findAttachments');
```
Comment (allenmanning) [inline src/publish/confluence/confluence-helper.ts:836]: @allenmanning remove console logs

File: tests/docs/smoke-all/confluence/.gitignore [hunk 2]
```diff
@@ -1,4 +1,6 @@
 _publish.yml
 *.xml
+5815-confluence-links-to-file-attachments-not-supported_files
+*.html
```
Comment (cderv) [inline tests/docs/smoke-all/confluence/.gitignore:4]: Do you need to add this specifically for this example ? 

I don't think we add all the smoke-all folders into this gitignore. So I am wondering what is specific about this one ? 

The html and resources files should be cleaned up after the smoke test

**Review by cderv — COMMENTED** [review]
Do you want us to test it on Confluence ? I assuming you did. 

One question though:  the linked issue says

> The image is uploaded as an attachment to the document and linked. The link works and opens the attached file. Different file types are supported.

Is the image uploaded anyway ? Quarto is able to detect and send in the bundle  ? 

Just want to be sure because I don't see a specific change that would add the found image as a resource to upload... But I don't know well confluence format. :)

Otherwise looks good !
