### PR TITLE
Jupyter - fix `retrieve_nb_from_cache` regression

### LINKED ISSUE #9618: Error when accessing the jupyter cache
### Bug description

With activated Jupyter cache, the second run (and further runs, until I add `--cache-refresh` ) of a quarto document fails when accessing the cache. Happens with Python and Julia.

### Steps to reproduce

test1.qmd:

````qmd
---
title: test1
cache: true
---

```{python}
1+1
```
`````

$ export QUARTO_PRINT_STACK=true
$ quarto render  test1.qmd --to html
....fine.....
$ quarto render  test1.qmd --to html
```
Starting python3 kernel...ERROR:

expected str, bytes or os.PathLike object, not builtin_function_or_method
ERROR: Error
    at renderFiles (file:///opt/quarto/bin/quarto.js:77871:29)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async render (file:///opt/quarto/bin/quarto.js:82687:21)
    at async Command.actionHandler (file:///opt/quarto/bin/quarto.js:82835:32)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8015:13)
    at async Command.parseCommand (file:///opt/quarto/bin/quarto.js:7905:20)
    at async quarto (file:///opt/quarto/bin/quarto.js:117893:5)
    at async file:///opt/quarto/bin/quarto.js:117905:9
    at async mainRunner (file:///opt/quarto/bin/quarto.js:117798:9)
    at async file:///opt/quarto/bin/quarto.js:117896:5
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### Your environment

Linux Debian 12,
 Quarto 1.5.32

### Quarto check output

```
Quarto 1.5.32
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.13: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.32
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.8
      Path: /home/hellmund/Quarto/.venv/bin/python3
      Jupyter: 5.7.2
      Kernels: python3, julia-1.10, julia-1.8, cadabra2

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /usr/lib/R
      LibPaths:
        - /home/hellmund/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.46
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

### PR DESCRIPTION
**Pull request by cscheid**
Closes #9618.

### CODE REVIEW

**Comment by cscheid** [comment]
@cderv I'll need some help from you in setting up those `Pipfile` and `Pipfile.lock` files. I changed the Pipfile but my attempt to `PIPENV_IGNORE_VIRTUALENVS=1 pipenv install jupyter_cache` ended up with a totally different `Pipfile.lock`.

**Comment by cderv** [comment]
>  ended up with a totally different Pipfile.lock.

I don't know how different it was. Running `pipenv install` will re-lock from the `PipFile` - this means that everything will be resolved again to latest as we don't pinned version that much (using `"*"` for all our deps). 

So the `Pipfile.lock` will end up different as everything could be updated. Running `pipenv update jupyter-cache` can have less impact and it should only tweak the dependencies from the package and do not resolved the rest. 

I did that here, let's see if this works ok. There could be some OS tweak unfortunately as Python dependencies management is bad cross-OS. I'll handle windows, but you should check on Mac maybe

File: tests/test.ts [hunk 1]
```diff
@@ -176,7 +176,8 @@ export function test(test: TestDescriptor) {
           try {
             await test.execute();
           } catch (e) {
-            logError(e)
+            logError(e);
+            fail("Uncaught exception in test\n" + e.message);
```
Comment (cderv) [inline tests/test.ts:180]: I believe this breaks some tests because we have some mechanism to test the error message 
https://github.com/quarto-dev/quarto-cli/blob/ec4a95f0787bfc0f9ce1e925930fc7b3e4d35224/tests/verify.ts#L95-L109

Now, any test using `printsMessage()` as a verify function will fail.

Comment (cscheid) [reply tests/test.ts:180]: Hm. That's fair and I'll revert it, but this seems like the kind of thing we should fix. Because if we have a test that fails with an uncaught exception, it currently looks like the test passes.

Comment (cderv) [reply tests/test.ts]: What is an uncaught exception here ? 

I though we had `noErrors` and `noErrorsOrWarnings` to use in tests when we want to fail test on exceptions 
https://github.com/quarto-dev/quarto-cli/blob/ec4a95f0787bfc0f9ce1e925930fc7b3e4d35224/tests/verify.ts#L45-L93

Our smoke-test workflow defaults on `noErrorsOrWarnings` and allow to specify `noErrors` in `_quarto.tests`. 
https://github.com/quarto-dev/quarto-cli/blob/ec4a95f0787bfc0f9ce1e925930fc7b3e4d35224/tests/smoke/smoke-all.test.ts#L104-L115

https://github.com/quarto-dev/quarto-cli/blob/ec4a95f0787bfc0f9ce1e925930fc7b3e4d35224/tests/smoke/smoke-all.test.ts#L145-L147

In non smoke-test, we default to `noErrorsOrWarnings` in `testProjectRender()`, but in other function either `noErrorsOrWarnings` or `noErrors` usually needs to be added among verify functions. 

Hopefully, this is relevant, and I understood correctly your feedback, and it helps.

Comment (cscheid) [reply tests/test.ts]: I had a bug in this test https://github.com/quarto-dev/quarto-cli/blob/04524462d5653b57969db2daa49a0b4dfc13bc19/tests/smoke/jupyter/cache.test.ts where I used the wrong path, and so `await quarto` threw an exception. (Locally for me at least) the test passed, because we don't fail tests with uncaught exceptions.

Comment (cderv) [reply tests/test.ts]: I see. My understanding is that if you use `verify: [noErrorsOrWarnings],` instead of `verify: [],`, the error would have been caught. Maybe we should have another test wrapper that does default to this.

Comment (cderv) [reply tests/test.ts]: I agree. At least `testQuartoCmd()` should have this as default it seems. `test()` is more generic, but I agree it would be better to have it by default too.  

We could try change our functions to add a default and see if the tests suites still pass ? 🤷‍♂️
