### PR TITLE
Fix refs positionning using a div for PDF output 

### LINKED ISSUE #6867: The location of references list is not assigned by `#refs` block
### Bug description

The location of references list is not assigned by `#refs` block

## Step 1: create book project 

```
quarto create-project mybook --type book
```

## Step 2: modify `_quarto.yml` as follow

I add an appendix after  the references.

```
project:
  type: book

book:
  title: "mybook"
  author: "Norah Jones"
  date: "9/17/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd
  appendices:
    - summary.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book
    keep-tex: true

```

### Expected behavior

The references's location is assigned by `#refs` block.

### Actual behavior

The following block doesn't work when output is pdf.

```
::: {#refs}
:::
```

the location of references list is not assigned by `#refs` block

截屏2023-09-18 09 00 39

references append to appendix.

截屏2023-09-18 08 59 18

### Your environment

- RStudio 2023.06.2+561 "Mountain Hydrangea" Release (de44a3118f7963972e24a78b7a1ad48b4be8a217, 2023-08-25) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.06.2+561 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36
- macOS 13.5.2 (22G91) 

### Quarto check output

```bash
quarto check
```

```

Quarto 1.4.369
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.369
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/xiangyun/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /usr/local/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.44
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK


```

### LINKED ISSUE #7432: Bibliography placement not working in v1.4
### Bug description

Since I installed v1.4 the placement of the bibliography doesn't work anymore. Before it worked with the following comment which is also stated in the Quarto documentation:

```
::: {#refs}
:::
```

### Steps to reproduce

````
---
title: "Title"
author: "Benjamin Schlegel"
format: 
  pdf:
    documentclass: scrreprt
bibliography: https://benjaminschlegel.ch/files/bibliography.bib
execute:
  echo: false
---

# Intro

@Kriesi2006 blablabla...

```{r}
# some R code for the appendix
```


# Bibliography

::: {#refs}
:::


# Appendix

```{r ref.label=knitr::all_labels()}
#| echo: true
#| eval: false

```
````

### Expected behavior

Bibliography should be printed at the place of:

```
::: {#refs}
:::
```

### Actual behavior

It gets printed at the end of the document after the appendix.

### Your environment

- IDE: 

RStudio 2023.06.0+421 "Mountain Hydrangea" Release (583b465ecc45e60ee9de085148cd2f9741cc5214, 2023-06-05) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.06.0+421 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36

- OS: Windows 11 Pro 22H2 22621.2506

### Quarto check output

$ quarto check
Quarto 1.4.460
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.460
      Path: C:\Users\benja\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\benja\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.12 (Conda)
      Path: C:/ProgramData/Anaconda3/python.exe
      Jupyter: 4.9.2
      Kernels: python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 22, in <module>
    from IPython.core.application import (
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\__init__.py", line 52, in <module>
    from .terminal.embed import embed
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\terminal\embed.py", line 15, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 73, in <module>
    from IPython.core.history import HistoryManager
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\history.py", line 11, in <module>
    import sqlite3
  File "C:\ProgramData\Anaconda3\lib\sqlite3\__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "C:\ProgramData\Anaconda3\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed while importing _sqlite3: Das angegebene Modul wurde nicht gefunden.
(|) Checking Jupyter engine render....

Kernel died before replying to kernel_info
[>] Checking Jupyter engine render....OK

### PR DESCRIPTION
**Pull request by cderv**
This should fix #6867 

As discussed, this is a regression in 1.4 due to some change at #6620 regarding flattening the divs in `coalesce_raw()` at `src\resources\filters\quarto-finalize\coalesceraw.lua`

This PR complements the fix at #6952 by also checking for empty ids on the Div before doing the flattening. 

@cscheid is that too wide ? We could just disallow flattening for div with id `refs` if needed. I am not too sure why we would flatten in LaTeX all the div of the document - but you know better. 

Also I added some tests. For that, I thought about your Lua testing tricks. But it required to add and entry point at the very end . 
Is that ok ? 

Otherwise, classic test is to check inside output. 

To prevent regression, I also added some tests about the refs positioning feature for natbib and biblatex, which is a Quarto feature (https://quarto.org/docs/authoring/footnotes-and-citations.html#bibliography-generation) cc @dragonstyle I did not found any for this feature

### CODE REVIEW

File: src/resources/filters/main.lua [hunk 1]
```diff
@@ -426,7 +426,9 @@ table.insert(quarto_filter_list, { name = "pre-render", filter = {} }) -- entry
 tappend(quarto_filter_list, quarto_layout_filters)
 tappend(quarto_filter_list, quarto_post_filters)
 table.insert(quarto_filter_list, { name = "post-render", filter = {} }) -- entry point for user filters
+table.insert(quarto_filter_list, { name = "pre-finalize", filter = {} }) -- entry point for user filters
```
Comment (cscheid) [inline src/resources/filters/main.lua:429]: I wonder if we should use a slightly "less public" name here. For example, you can use `finalize-combined` directly, since that's the name of the first finalize filter.

We haven't documented this part yet, but the `pre-` and `post-` names are meant to be "stable API entrypoints". `pre-finalize` and `post-finalize` are good names, but I was planning on not advertising the "finalize" part of the pipeline, because I'm not sure it's really necessary. This isn't a big deal either way, and we can keep this pair of names without advertising them.

File: src/resources/filters/quarto-finalize/coalesceraw.lua [hunk 2]
```diff
@@ -22,7 +22,8 @@ function coalesce_raw()
       Div = function(div)
         -- only flatten out divs that have no classes or attributes
         -- (see https://github.com/quarto-dev/quarto-cli/issues/6936)
-        if #div.classes == 0 and #div.attributes == 0 then
+        -- or empty identifier (see https://github.com/quarto-dev/quarto-cli/issues/6867)
+        if #div.classes == 0 and #div.attributes == 0 and div.identifier == "" then
```
Comment (cscheid) [inline src/resources/filters/quarto-finalize/coalesceraw.lua:26]: This is a simple and very good fix. Thank you!

File: src/resources/filters/main.lua (hunk 1 above)
Comment (cderv) [reply src/resources/filters/main.lua:429]: I added `pre-finalize` just to follow the other names, as I needed the `post-finalize`. 

My understanding is that `post-render()` would have the same place anyway right. 

> For example, you can use finalize-combined directly, since that's the name of the first finalize filter.

I used the internal names to debug this - that is how I found `finalize-coalesce-raw` was the problem. 

I am ok to remove this and use `finalize-combined` for testing at start of finalize, but for end, I added `post-finalize` because I thought `finalize-typst-state` as last step would not be stable. 

> I wonder if we should use a slightly "less public" name here.

Ok with that totally. Though usually, undocumented means often not that public :) So if we don't document then it stays hidden (a little). Though we could make clear that it is not to be used except for testing. 

So overall: 
* Ok to remove `pre-finalize` 
* but `post-finalize` should stay right ? Or can we insert lua for testing at the very end another way ?

File: src/resources/filters/quarto-finalize/coalesceraw.lua (hunk 2 above)
Comment (cderv) [reply src/resources/filters/quarto-finalize/coalesceraw.lua:26]: Cool !

**Comment by cscheid** [comment]
> I am not too sure why we would flatten in LaTeX all the div of the document - but you know better.

One of the reasons is that divs are useful to organize the AST internally, but they are "useless" in LaTeX, except that they introduce a line break (because they're blocks), and often we don't want extra line breaks in LaTeX.

File: src/resources/filters/main.lua (hunk 1 above)
Comment (cscheid) [reply src/resources/filters/main.lua:429]: > So overall:
> 
> * Ok to remove `pre-finalize`
> * but `post-finalize` should stay right ? Or can we insert lua for testing at the very end another way ?

You're right that we currently don't have a "at-the-very-end" entry point. I guess that's enough to convince me to keep `finalize` as a real "stage" of our filter. Let's just leave both `pre-finalize` and `post-finalize`. We already have redundant names anyway, and that's on purpose (it's in case we move the filter steps, then they might stop being redundant)

**Comment by cderv** [comment]
> except that they introduce a line break (because they're blocks)

That was my missing point ! Good to know !
