### PR TITLE
Stop being clever about breadcrumb titles and just use the pipeline

### LINKED ISSUE #5046: Mobile breadcrumb isn't quite right
### Bug description

Hi there, I just noticed the mobile breadcrumb doesn't show the 2nd tier correctly... This should probably be 

Formats > Presentations > PowerPoint

Looks like it shows the first link in that second menu instead?   

I see it happening on quarto.org as well as my project. Thank you!

mobile-breadcrumb

---

OS: MacOS 3.2.1 (22D68)

quarto check:
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.296
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: 5.2.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library
      knitr: 1.38
      rmarkdown: 2.13

[✓] Checking Knitr engine render......OK

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

### PR DESCRIPTION
**Pull request by dragonstyle**
This fixes #5046 the correct way, avoid conflict and duplication driven by trying to pick the title of the breadcrumb out of the sidebar DOM post render.

### CODE REVIEW

File: src/project/types/website/website-navigation-md.ts [hunk 1]
```diff
@@ -192,6 +196,39 @@ const prevPageTitleHandler = (context: NavigationPipelineContext) => {
   };
 };
 
+const safeKey = (key: string) => {
```
Comment (allenmanning) [inline src/project/types/website/website-navigation-md.ts:199]: @dragonstyle I'm not sure if refactoring to a Pure Function with unit tests would make sense here, but I thought I would suggest it.  There is growing complexity in this area.

Comment (dragonstyle) [reply src/project/types/website/website-navigation-md.ts:199]: This overall change looks a lot more complicated than it really is. The root issue here was my decision to try to reuse the rendered sidebar to compute the proper rendered contents of the breadcrumbs by just plucking the contents of the sidebar from the DOM. This is ok in normal cases, but in some cases (for example, sections in the sidebar which are just text with no href), it breaks down. Rather than doing the "clever" thing, this ultimately just does what we do pretty much everywhere else- just render the contents of the breadcrumbs with our markdown pipeline. Most of the diff (especially in website navigation is just removing a few lines of code and moving code).

The growing complexity I think reflected a couple failed attempts to fix the issue with band aids and finally this, the actual fix :)
