### PR TITLE
Correctly handle name attributes for proof envs

### LINKED ISSUE #7265: Proof Remark and Solution environment does not work when name provided anymore
````markdown
---
title: "failing solution env"
format: 
  pdf: default
keep-md: true
---

### Solution

::: {.solution name="The solution"}
The solution
:::

````

````
Error running filter C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/resources/filters/main.lua:
...R/QUARTO~2/src/resources/filters/./crossref/theorems.lua:65: bad argument #2 to 'concat' (table expected, got string)
stack traceback:
	...R/QUARTO~2/src/resources/filters/./crossref/theorems.lua:65: in function <...R/QUARTO~2/src/resources/filters/./crossref/theorems.lua:35>
	(...tail calls...)
	[C]: in ?
	[C]: in method 'walk'
	...V_R/QUARTO~2/src/resources/filters/./ast/customnodes.lua:78: in function <...V_R/QUARTO~2/src/resources/filters/./ast/customnodes.lua:68>
	(...tail calls...)
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:40: in local 'callback'
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:54: in upvalue 'run_emulated_filter_chain'
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:89: in function <..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:86>
stack traceback:
	...V_R/QUARTO~2/src/resources/filters/./ast/customnodes.lua:78: in function <...V_R/QUARTO~2/src/resources/filters/./ast/customnodes.lua:68>
	(...tail calls...)
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:40: in local 'callback'
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:54: in upvalue 'run_emulated_filter_chain'
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:89: in function <..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:86>
`````

This syntax is documented at https://quarto.org/docs/authoring/cross-references.html#theorems-and-proofs

> As with theorems you can optionally include a heading as the first element of the div (or a name attribute) to give the environment a caption for typesetting (this typically appears in parentheses after the environment title).

Same with other syntax which is adding a header inside 
````markdown
---
title: "failing solution env"
format: 
  pdf: default
keep-md: true
---

### Solution

::: {.solution}

# The solution

The solution
:::
````

This is with Quarto 1.4 latest pre-release on Windows.

### PR DESCRIPTION
**Pull request by cderv**
without breaking qed symbol handling as this is a regression from #7139Welcome to the quarto GitHub repo!

This fix #7265 regression and adapt tests for checking output. 

It also adds support for special content from **bookdown** experience.

### CODE REVIEW

File: src/resources/filters/crossref/theorems.lua [hunk 1]
```diff
@@ -59,29 +59,35 @@ function crossref_theorems()
 
           -- output
           if _quarto.format.isLatexOutput() then
-            local begin_env = "\\begin{" .. proof.env .. "}"
-            local preamble = pandoc.Plain(pandoc.RawInline("latex", begin_env))
+            local preamble = pandoc.List()
+            preamble:insert(pandoc.RawInline("latex", 
+              "\\begin{" .. proof.env .. "}"))
```
Comment (cderv) [inline src/resources/filters/crossref/theorems.lua:64]:
```suggestion
            preamble:insert(pandoc.RawInline("latex", "\\begin{" .. proof.env .. "}"))
```

No need for newline
